### ISSUE TITLE
[Bug Report] When changing volume the bot stops playing/crashes

### ISSUE THREAD

**Issue by maikhunt** [jagrosh/MusicBot#306] opened 2019-10-24 15:12 UTC
**Describe the bug**
When you type volume xx, the bot crashes and leaves the Discord voice channel

**To Reproduce**
1. type "volume xx" eg. "volume 50"

**Expected behavior**
The player should change playback volume

**Screenshots**

**Version Info (please complete the following information):**
 - Operating System:  Windows 10 64bit
 - JMusicBot Version: 0.2.5

**Additional context**

**Comment by jagrosh** [comment] 2019-10-24 16:17
Duplicate of #300, you're running 32 bit java. Switch to 64 bit java.

**Closed by jagrosh** 2019-10-24 16:17 UTC
