### ISSUE TITLE
[Bug Report]  Error loading: Video returned by YouTube isn't what was requested 

### ISSUE THREAD

**Issue by RyuguDev** [jagrosh/MusicBot#1550] opened 2024-04-21 17:27 UTC
### Bug Description

Every video i will play, the bot answers with " Error loading: Video returned by YouTube isn't what was requested "

### Steps to Reproduce

download latest and used +music play as command

### Expected Result

playing music

### Debug Output

```
System Properties:
  java.version = 17.0.10
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 17.0.10+7-Ubuntu-120.04.1
  java.specification.version = 17
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.4.0
  Owner = 587341983396397066
  Prefix = +music
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 727959e9f621fc457b3a5adafcfffb55fdeaa538-SNAPSHOT

Runtime Information:
  Total Memory = 80
  Used Memory = 22

Discord Information:
  ID = 737537444723032086
  Guilds = 8
  Users = 5
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by josephsamela** [comment] 2024-04-21 23:05
Same issue! 
![image](https://github.com/jagrosh/MusicBot/assets/16111451/ddd658c1-5b27-4a2e-a04b-a52ab0148487)

**Comment by jagrosh** [comment] 2024-04-21 23:32
Duplicate of #1527 , please check existing issues before posting.

**Closed by jagrosh** 2024-04-21 23:32 UTC
