### ISSUE TITLE
[Bug Report] Most youtube videos don't work

### ISSUE THREAD

**Issue by MrTalon62** [jagrosh/MusicBot#372] opened 2020-03-23 21:47 UTC
**Describe the bug**
When I try to play video from youtube it says in console this https://pastebin.com/5sTvV3Zg

**To Reproduce**
1. -play https://www.youtube.com/watch?v=2Nc-X1wlU3Q
that's all

**Expected behaviour**
Just play a video as normal

**Screenshots**

**Debug Info**
Docker container, latest version

**Comment by POPLOPUK** [comment] 2020-03-23 23:41
Duplicate of #369. You should wait for the next Jar release or compile the jar file yourself.

**Closed** 2020-03-24 00:24 UTC
