### ISSUE TITLE
[Feature Request] Make bot to disconnect when admin press "disconnect" button

### ISSUE THREAD

**Issue by Tavinen** [jagrosh/MusicBot#367] opened 2020-03-21 12:48 UTC
**Is your feature request related to a problem? Please describe.**
While I listen to the music and had to stop the bot to focus on the match, it's hard to make my bot to leave the voice chat by typing the command

**Describe the solution you'd like**
Make "disconnect" button to function
**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Make faster disconnection of the bot

**Comment by Sanduhr32** [comment] 2020-03-21 12:52
The disconnect button in the discord client ui is kicking the bot out of the voice channel.
The bot can't read that you pressed the button.
It **gets disconnected by discord** and is not disconnecting on it's own.

**Comment by Tavinen** [comment] 2020-03-21 13:03
But can you make it disconnected by discord?

**Comment by Sanduhr32** [comment] 2020-03-21 13:38
Dude, that is what the button "Disconnect" does when you press it.

**Comment by OscarGamerYT** [comment] 2020-03-22 19:28
You can make an event handler. When host(user that invites the bot to the voice channel) leaves the channel, the bot also leaves the channel and stop the music.

**Comment by jagrosh** [comment] 2020-06-23 19:05
The way you've described it most recently seems like a duplicate of an already-planned feature, which is being able to set an action for when the bot is in an empty voice channel.

**Closed by jagrosh** 2020-06-23 19:05 UTC
