### ISSUE TITLE
[Bug Report] Cant play music

### ISSUE THREAD

**Issue by AngelKotik** [jagrosh/MusicBot#543] opened 2020-10-30 23:54 UTC
**Describe the bug**
When i type [prefix]play (song), bot join channel, then leave

**To Reproduce**
1. Run with host
2. Do a command [prefix]play (music)

**Error**
https://303.is-inside.me/znjFLk5A.txt

**Debug Info**
https://303.is-inside.me/5nxrjeP5.txt

**Comment by mkgaming54** [comment] 2020-10-31 04:03
Same issue :(

**Comment by Comstepr** [comment] 2020-10-31 05:07
This could be related to the 429 issue. The current way to try and fix this is to download the video and save it locally, then play it with the bot.

**Comment by onlyyouX2** [comment] 2020-10-31 09:00
Same issue here.

**Comment by AgutinVBoy** [comment] 2020-10-31 09:45
Same issue

**Comment by MetrixYT** [comment] 2020-10-31 09:45
I am having the same issue, it's been happening for a while now.

**Comment by Sanduhr32** [comment] 2020-10-31 10:03
Duplicate of #531

**Closed** 2020-10-31 10:11 UTC
