### ISSUE TITLE
[Bug Report] prefix and music player is broken

### ISSUE THREAD

**Issue by sophienix** [jagrosh/MusicBot#1781] opened 2024-12-09 14:25 UTC
### Bug Description

custom prefixes will not work on server the only prefix that works is the @mention prefix the custom prefix only seems to work in private DM
![image](https://github.com/user-attachments/assets/5c543043-8eb0-46cd-a872-3db25222d454)

### Steps to Reproduce

1. be on any version
2. set a custom prefix in config file or using a command
3. use help command

### Expected Result

It should use the prefix just like any other bot

### Debug Output

```
System Properties:
  java.version = 17.0.4
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 17.0.4+11-LTS-179
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.3
  Owner = private
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 37
  Used Memory = 21

Discord Information:
  ID = private
  Guilds = 2
  Users = 5
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3 main

**Comment by sophienix** [comment] 2024-12-09 15:16
i am now having this issue 
![image](https://github.com/user-attachments/assets/e02b5d93-100f-41c0-ba8f-861caacd5cdb)

**Comment by sophienix** [comment] 2024-12-09 15:16
seems like the bot is unusable for me and i dont know why tried on a different device still doesn't work i have also used older versions

**Comment by MichailiK** [comment] 2024-12-09 17:20
Duplicate of: 
- #1215
- #1588

**Closed as not planned by MichailiK** 2024-12-09 17:20 UTC
