### ISSUE TITLE
[Bug Report] Title Here 

### ISSUE THREAD

**Issue by shawchip** [jagrosh/MusicBot#1730] opened 2024-10-20 09:08 UTC
### Bug Description

Hello, I was using this bot when all of a sudden it stopped working, i checked the console and i cant understand anything

console:
[10:47:10] [INFO] [JMusicBot]: Loaded config from C:\Users\leoxa\Documents\MusicBot\config.txt
[10:47:13] [INFO] [JDA]: Login Successful!
[10:47:14] [INFO] [JMusicBot]: JMusicBot
[10:47:14] [INFO] [WebSocketClient]: Connected to WebSocket
[10:47:14] [INFO] [JDA]: Finished Loading!
[10:49:10] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/e627e516/player_ias.vflset/fr_FR/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\leoxa\AppData\Local\Temp\lavaplayer-yt-player-script1876170928962009669.js
[10:49:11] [ERROR] [AudioHandler]: Track aUG--f5qZjo has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

Start the bot

### Expected Result

Have my music played

### Debug Output

```
System Properties:
  java.version = 17.0.9
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 17.0.9+9
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.3
  Owner = 1297289242686525611
  Prefix = +
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 37
  Used Memory = 19

Discord Information:
  ID = 1006529936103845909
  Guilds = 2
  Users = 2
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [x] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

latest 0.4.3

**Comment by MichailiK** [comment] 2024-10-20 11:22
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-20 11:22 UTC
