### ISSUE TITLE
[Bug Report] 0.4.0 version with Pebblehost

### ISSUE THREAD

**Issue by Olexijl** [jagrosh/MusicBot#1535] opened 2024-04-01 17:09 UTC
### Bug Description

Hello there,

Since some time ago I use jagrosh Music Bot, currently 0.3.9 - with Pebblehost hosting. As it seems the 0.3.9 works reliable and I don't have any issues.

Tried to update to 0.4.0, uploaded it to Pebblehost, set it up there, kicked & reinvited the bot to the server. While it joins the voice channel set up for him, it doesn't play any music on command - while 0.3.9 does!

I cannot tell if it is something wrong with the bot or with the server on hosting. Is it bcz Java 11 is required, instead of 8?

### Steps to Reproduce

1. Use Pebblehost.com as hosting for the jagrosh Music Bot. It costs you 3 USD montly. Upload the 0.4.0 JAR file inc. config.txt to the server.
2. Set up the configuration to JMusicBot-0.4.0.jar to execute, while the version of Java (pebble-java-config.json)  from 8 to 11.
3. Create the bot in Developer Portal of discord.
4. Invite the bot as told in the Wiki to your server.
5. Pebblehost do have BIG buttons, START/STOP/RESTART on their server. Check if these do start and stop the bot in your discord server. They should.
6. Check if playing YouTube videos do work. IT SHOULDN'T! That's the bug... No playing of URL's or videos (though other than playing - it should work all)...

### Expected Result

Joining the voice channel, executing command correctly, no playback 

### Debug Output

Windows 11 23H2, 0.4.0 Jagrosh Music Bot

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-04-10 16:10
This is either a host-specific issue (thus out-of-scope for this repo), or a duplicate of one of the existing issues.

**Closed by jagrosh** 2024-04-10 16:10 UTC

**Comment by softcheese112** [comment] 2024-05-01 23:38
Did anyone find a fix to this? Because I'm getting it aswell, and if it were an host issue, what could I ask the host to fix in that case?
