### ISSUE TITLE
[Bug Report] Error loading track (youtube link)

### ISSUE THREAD

**Issue by 0lotus0flower0** [jagrosh/MusicBot#326] opened 2019-11-17 08:11 UTC
Hi
The update 0.2.6 was nice and the YouTube links were working normally
However, it has become not working and tried to change the server to a new server also does not work When you turn on the YouTube link shows the error
  (Error loading track).I downgraded to version 0.2.5 was working on some servers without problems
  Ubuntu 16 64 systems
A picture of the error that appears
Thanks for your patience
Greetings to you
![Screenshot (111)](https://user-images.githubusercontent.com/57845660/69004819-548ca000-092a-11ea-91a1-1a6c4e39e356.png)

**the error **
Bot-0.2.6-Linux.jar
[08:42:37] [ERROR] [Startup]: Could not start GUI. If you are running on a serve                                     r or in a location where you cannot display a window, please run in nogui mode u                                     sing the -Dnogui=true flag.
[08:42:37] [INFO] [Startup]: Loaded config from /root/MusicBot2/src/main/java/co                                     m/jagrosh/jmusicbot/config.txt
[08:42:38] [INFO] [JDA]: Login Successful!
[08:42:38] [INFO] [WebSocketClient]: Connected to WebSocket
[08:42:47] [INFO] [JDA]: Finished Loading!
[08:43:05] [WARN] [DefaultAudioPlayerManager]: Suspicious exception for loading                                      item https://www.youtube.com/watch?v=3cf3C8i-70Y&list=RD3cf3C8i-70Y&start_radio=                                     1
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Could not find tracks                                      from mix.
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMixProvider.lo                                     adMixWithId(YoutubeMixProvider.java:98)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceMan                                     ager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:249)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceMan                                     ager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:228)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRou                                     ter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:91)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRou                                     ter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:61)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRou                                     ter.route(DefaultYoutubeLinkRouter.java:39)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceMan                                     ager.loadItemOnce(YoutubeAudioSourceManager.java:196)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceMan                                     ager.loadItem(YoutubeAudioSourceManager.java:133)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.che                                     ckSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.che                                     ckSourcesForItem(DefaultAudioPlayerManager.java:419)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lam                                     bda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnabl                                     e.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnabl                                     e.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                     java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                     .java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jagrosh** [comment] 2019-11-17 08:19
Duplicate of #313

**Closed by jagrosh** 2019-11-17 08:19 UTC
