### ISSUE TITLE
Bot acknowlodging command and joins the voice channel but immediatly leaves

### ISSUE THREAD

**Issue by Xgrret** [jagrosh/MusicBot#1743] opened 2024-10-27 14:21 UTC
### Bug Description

Ye se when playing a music the bot proceeds to join the channel but leaves immediatly.

[14:05:37] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/fb725ac8/player_ias.vflset/fr_FR/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\chise\AppData\Local\Temp\lavaplayer-yt-player-script17302943754791927703.js
[14:05:37] [ERROR] [AudioHandler]: Track yMbGDlwoE8Q has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

1. use any bot command that plays music
2. bot join in vc
3. immediatly leaves

### Expected Result

I expected for the bot to join in and play the music but he instantly elaves instead

### Debug Output

[14:05:37] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/fb725ac8/player_ias.vflset/fr_FR/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\chise\AppData\Local\Temp\lavaplayer-yt-player-script17302943754791927703.js
[14:05:37] [ERROR] [AudioHandler]: Track yMbGDlwoE8Q has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

most recent

**Comment by MichailiK** [comment] 2024-10-27 15:49
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-27 15:49 UTC
