### ISSUE TITLE
[Bug Report] Music playing channel shifting 

### ISSUE THREAD

**Issue by RootAndroid58** [jagrosh/MusicBot#283] opened 2019-10-10 14:53 UTC
**Describe the bug**
here in this case my channel has for example and the bot is in 1 voice channel and if no one is listening to the channel the bot gives error message to go to channel 1 instead of shifting to channel 2

**To Reproduce**
1. connect to any voice channel channel and play a music (any) 
2. move to voice channel 2 and try adding the music
3. error appears `You must be listening in GENERAL to use that!`

**Expected behavior**
shift to voice channel 2 if no one other than bot is connected

 - Operating System:  Windows 64bit
 - JMusicBot Version:  0.2.5

Sry for bad english or grammer

**Comment by jagrosh** [comment] 2019-10-10 16:06
Duplicate of #245

**Closed by jagrosh** 2019-10-10 16:06 UTC
