### ISSUE TITLE
Youtube Music Playlists don't work anymore

### ISSUE THREAD

**Issue by iasoskaf** [jagrosh/MusicBot#1152] opened 2022-04-08 09:30 UTC
### Bug Description

I used to be able to use youtube Music playlists using your bot, suddenly it stopped working. Links like this : 
https://music.youtube.com/watch?v=zTJNaZ9AgFE&list=RDAMPLOLAK5uy_nsxcWRAlYsChn8B-YggqS_2n4WQuCitZ4

However now i get a "Could not load track" error. Before i would just press the emoji icon to load all the tracks.

### Steps to Reproduce

1. Input the playlist listed above ro any youtube music playlist
2. Get error.

### Expected Result

I expected for all the tracks to load and start playing.

### Debug Output

.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-04-08 09:40
Duplicate of #1147

**Closed by MichailiK** 2022-04-08 09:40 UTC
