### ISSUE TITLE
[Bug Report] [lavaplayer] Trying to play any YouTube videos results in a 404

### ISSUE THREAD

**Issue by MichailiK** [jagrosh/MusicBot#371] opened 2020-03-23 21:24 UTC
**Describe the bug**
Trying to play a YouTube videos now results to this exception being printed to the console:
```
[22:12:30] [ERROR] [LocalAudioTrackExecutor]: Error in playback of UelDrZ1aFeY
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: Received non-success response code 404
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
	... 4 common frames omitted

```

**To Reproduce**
Play any YouTube video

**Expected behavior**
For... the YouTube video to... play...

**Screenshots**
![image](https://user-images.githubusercontent.com/39029839/77364160-41fcfa00-6d54-11ea-9447-7438f9a2200d.png)

**Debug Info**
Not applicable.

**Additional context**
There already exists an issue over at lavaplayer: sedmelluq/lavaplayer#282. It seems like YouTube has changed stuff which is causing this issue.
I will close this issue when sedmelluq/lavaplayer#282 closes.

**Comment by jagrosh** [comment] 2020-03-23 21:24
Duplicate of #370

**Closed by jagrosh** 2020-03-23 21:24 UTC
