### ISSUE TITLE
[Bug Report] Direct URLs don't work (LavaPlayer update)

### ISSUE THREAD

**Issue by ZackRuybal** [jagrosh/MusicBot#257] opened 2019-07-31 20:37 UTC
**Describe the bug**
Since around 2 days ago, old LavaPlayer versions stopped working for playing Youtube URLs directly. LavaPlayer has since been updated and it works, all that needs to happen is that update I suppose.

**To Reproduce**
1. Run command `-play https://www.youtube.com/watch?v=rY-FJvRqK0E` (for example)
2. Observe error in log, error in Discord text channel.

**Expected behavior**
Play the track, as it should be.

**Screenshots**
N/A

**Version Info (please complete the following information):**
 - Operating System: Ubuntu 16.04.6
 - JMusicBot Version: 0.2.3

**Additional context**
Log error:
```
[20:21:05] [ERROR] [DefaultAudioPlayerManager]: Error in loading item https://www.youtube.com/watch?v=rY-FJvRqK0E
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:217)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromUrlWithVideoId(YoutubeAudioSourceManager.java:307)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromMainDomain(YoutubeAudioSourceManager.java:244)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadNonSearch(YoutubeAudioSourceManager.java:314)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:189)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:128)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:213)
        ... 14 common frames omitted
```

**Comment by Sanduhr32** [comment] 2019-07-31 20:52
duplicate of #255

**Closed** 2019-07-31 22:09 UTC
