### ISSUE TITLE
Some songs result in error

### ISSUE THREAD

**Issue by RetroGEO** [jagrosh/MusicBot#551] opened 2020-11-02 19:32 UTC
Playing some(but not all) youtube URLS results in the following error in the console:

[13:28:47] [ERROR] [LocalAudioTrackExecutor]: Error in playback of CE5-rVP2InI
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:136)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	... 4 common frames omitted

**Comment by jagrosh** [comment] 2020-11-02 19:33
Duplicate of #531

**Closed by jagrosh** 2020-11-02 19:33 UTC

**Comment by RetroGEO** [comment] 2020-11-02 20:11
I don't see the line "Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null" in the other person's error message.

**Comment by MichailiK** [comment] 2020-11-02 20:14
The error is for the most part same & both need a fix to the cipher manager.

**Comment by RetroGEO** [comment] 2020-11-02 20:24
Got it. Thanks for the fast response and support!
