### ISSUE TITLE
This song is not playing

### ISSUE THREAD

**Issue by Adi2008-prog** [jagrosh/MusicBot#1749] opened 2024-11-01 12:05 UTC
https://music.youtube.com/watch?v=S6DhdT0NAzI

**Comment by xyzakaria** [comment] 2024-11-01 12:52
i cant have the bot playing song it keeps disconnecting from the vc , the console shows some error , the issue happend more than a month ago

**Comment by MichailiK** [comment] 2024-11-01 12:56
Likely duplicate of:

- #1588 
- #1682

**Closed as not planned by MichailiK** 2024-11-01 12:56 UTC

**Comment by Adi2008-prog** [comment] 2024-11-29 05:51
So what can I do? Or can u suggest any other app ditto as Vi music?
