### ISSUE TITLE
[Feature Request] Deafen itself

### ISSUE THREAD

**Issue by REMOOO** [jagrosh/MusicBot#540] opened 2020-10-30 10:32 UTC
**Is your feature request related to a problem? Please describe.**
Bandwidth saving

**Describe the solution you'd like**
Adding config option to deafen itself.
e.g. https://groovy.zendesk.com/hc/en-us/articles/360042923932-Why-does-Groovy-deafen-itself-

**Describe the basic flow/steps of using this feature**
How this feature would be used:

1. boolean config option: deafen_itself=true/false
2. bot would deafen itself to save bandwidth
3. default to true

**Additional context**
Config option

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1

**Comment by jagrosh** [comment] 2020-10-30 10:35
Duplicate of #519

**Closed by jagrosh** 2020-10-30 10:35 UTC

**Comment by kubo6472** [comment] 2020-11-03 15:59
@REMOOO have you literally just copied out text from my issue? :D lol
