### ISSUE TITLE
[Bug Report] Play Music Error

### ISSUE THREAD

**Issue by iNaruse** [jagrosh/MusicBot#381] opened 2020-04-09 09:39 UTC
`
[18:38:49] [ERROR] [LocalAudioTrackExecutor]: Error in playback of SYo7GMuUacY
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Received non-success response code 404
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
	... 4 common frames omitted
`

how to fix??

**Comment by Sattishh** [comment] 2020-04-09 10:04
Look at issue #380 that will fix your doubt. Danny did a great work resolving it.
https://github.com/jagrosh/MusicBot/issues/380

**Comment by iNaruse** [comment] 2020-04-09 10:14
How do you do "Bumping lavaplayer to 1.3.46"?

**Comment by jagrosh** [comment] 2020-04-09 13:20
Duplicate of #370

**Closed by jagrosh** 2020-04-09 13:20 UTC
