### ISSUE TITLE
[Feature Request] A Command To Add Sound Effects For The Audio

### ISSUE THREAD

**Issue by UrafikiTheFluff** [jagrosh/MusicBot#1347] opened 2023-04-08 10:47 UTC
### Is your feature request related to a problem? Please describe.

not really

### What is your ideal solution to the problem?

not really

### How would this feature be used?

Youtube VIdeos/Song Channels To Use A Bot For Easy change Of Music Sound Effects
Chill Servers Just Wanting To Add A Little Style To Their Music And Change The Way It Sounds

### Additional Info

Any Cool Effects Like Nightcore Or Vaporwave Anything Cool Really 

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-01-31 15:31
Duplicate of #968 which would encompass multiple types of filters

**Closed by jagrosh** 2024-01-31 15:31 UTC
