### ISSUE TITLE
[Feature Request] Can be bound to multiple voice channels or a voice channel category.

### ISSUE THREAD

**Issue by ThatFlySamurai** [jagrosh/MusicBot#562] opened 2020-11-20 17:43 UTC
When you add a comma in the VC, command, you can set it to multiple voice channels.

Example: !VC general , gaming

Or you could set it to a category,

Example: !VCC Voice Channels

VCC stands for voice channel category. It is worth noting that with channel categories, the bot will connect to the channel with the person who gave the command to the bot. If no music is playing on the bot for more than 5 minutes, it will disconnect from the channel. People with DJ roles can !move the bot to a different VC.

**Comment by Sanduhr32** [comment] 2020-11-20 17:45
Uhm, can you express yourself more clearly about what you mean by following the template?

**Comment by jagrosh** [comment] 2020-11-20 17:54
Duplicate of #503

**Closed by jagrosh** 2020-11-20 17:54 UTC
