### ISSUE TITLE
[Feature Request] About reproduction of Youtube halfway

### ISSUE THREAD

**Issue by Satoki101** [jagrosh/MusicBot#208] opened 2019-02-23 01:28 UTC
I issued a URL specifying the playback position from Youtube's share and played from the beginning even if I requested with the "!! play" command, so when adding Youtube's song with the "!! play" command, I want you to be able to play from the middle such as specifying the number.

**Comment by jagrosh** [comment] 2019-02-23 02:09
Duplicate of [an existing planned feature](https://github.com/jagrosh/MusicBot/projects/1#card-1542748). In the future, please read the planned features list before making a request, and please use the feature request template.

**Closed by jagrosh** 2019-02-23 02:09 UTC
