### ISSUE TITLE
[Bug Report] Prefix not working

### ISSUE THREAD

**Issue by UT66** [jagrosh/MusicBot#1212] opened 2022-09-02 14:09 UTC
### Bug Description

Hi! I just setup the bot today and almost everything is working perfectly except for when I change the prefix in the config file.
When I change it to "!" the bot doesn't respond to any commands anymore, not when using the ! prefix or when @ing the bot. When I leave the prefix setting blank the bot works again and responds when I @ it

### Steps to Reproduce

1. Change prefix option in config file to "!"
2. Restart bot.
3. Bot doesn't respond :/

### Expected Result

I expected the bot to respond to the prefix so like when I type "!play *song*" 

### Debug Output

My system is POP!_OS 22.04 LTS 64bit and I'm using the latest JMusicBot version 0.3.8
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/9478518/debug_information.txt)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by treevar** [comment] 2022-09-02 18:50
@UT66 What does the debug info show for the prefix when you set it to "!"?

**Comment by Ad-Blokker** [comment] 2022-09-02 18:52
> @UT66 What does the debug info show for the prefix when you set it to "!"?

Same problem prefix set to "!" and the debug info shows it set on "!" maybe because discord rolled out a new feature? Related to the new bot command features?

**Comment by Ad-Blokker** [comment] 2022-09-02 18:56
No prefixes seem to work in my testing. I disabled the prefix in the config and it default to @BOTNAME and that works atleast

**Comment by jagrosh** [comment] 2022-09-02 19:00
Duplicate of #1207

**Closed by jagrosh** 2022-09-02 19:00 UTC
