### ISSUE TITLE
[Bug Report] Bot joins then immediately leaves

### ISSUE THREAD

**Issue by MrSnowmanASOY** [jagrosh/MusicBot#1564] opened 2024-05-05 05:29 UTC
### Bug Description

When a song is requested the bot will join the voice channel then immediately leave without playing anything.

### Steps to Reproduce

1. Install bot
2. Run bot with parameters `"C:\Program Files\Java\jdk-11\bin\java.exe" -Dnogui=true -jar JMusicBot-0.4.0.jar` (selected specifically java 11)
3. Request any song

### Expected Result

I expect the song will be played and the bot will leave shortly after the song finishes

### Debug Output

```
System Properties:
  java.version = 11.0.22
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 11.0.22+9-LTS-219
  java.specification.version = 11
  os.arch = amd64
  os.name = Windows 11

JMusicBot Information:
  Version = 0.4.0
  Owner = 1091514604548534323
  Prefix = @mention
  AltPrefix = m!
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 727959e9f621fc457b3a5adafcfffb55fdeaa538-SNAPSHOT

Runtime Information:
  Total Memory = 508
  Used Memory = 91

Discord Information:
  ID = 1236527235658158090
  Guilds = 1
  Users = 2
```

### Additional Info

I have linked a video to show what im talking about in more detail [here](https://youtu.be/uaj2DiDHduk)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2024-05-05 09:40
Duplicate of #1537

**Closed by MichailiK** 2024-05-05 09:40 UTC
