### ISSUE TITLE
[Feature Request] Blacklist user from adding songs

### ISSUE THREAD

**Issue by SQLuid** [jagrosh/MusicBot#1027] opened 2021-11-10 08:40 UTC
### Is your feature request related to a problem? Please describe.

We've had trolls play really weird songs and was wondering if it'd be possible to add a command that disables certain users from using commands

### What is your ideal solution to the problem?

A command allowing admins/bot owner to blacklist people from adding songs

### How would this feature be used?

When someone plays disturbing songs you can (temporarily) blacklist them from using commands

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by urbels** [comment] 2021-11-11 09:24
I use DJ only mode to avoid this. Add DJ role to trusted people and only they can add songs.

**Comment by MichailiK** [comment] 2021-11-13 18:49
Above, and basically a duplicate of #28

**Closed by MichailiK** 2021-11-13 18:49 UTC
