### ISSUE TITLE
[Feature Request] Always display "Nowplaying" at the bottom

### ISSUE THREAD

**Issue by Lapius7** [jagrosh/MusicBot#1650] opened 2024-08-06 17:42 UTC
### Is your feature request related to a problem? Please describe.

When you use "{prefix}np", the currently playing music information is displayed and updated continuously, but if you chat afterwards, it will start to flow, so every time you chat, a new one will be automatically sent. and make sure to delete what you sent earlier.

![image](https://github.com/user-attachments/assets/86dd3cd3-66e8-44f3-8ae5-7c115704cd39)

From Japan, GoogleTranslate

### What is your ideal solution to the problem?

Always show "Nowplaing" as a new chat

### How would this feature be used?

1, {prefix}np
2, If a new chat is made, delete the previous embed and send the embed again

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-08-06 19:53
Effectively a duplicate of #353 #607 (these should probably all be consolidated)

**Closed by jagrosh** 2024-08-06 19:53 UTC
