### ISSUE TITLE
[Feature Request] remove the limit on number of songs in the playlist 

### ISSUE THREAD

**Issue by UnconsciousPebble** [jagrosh/MusicBot#1415] opened 2023-08-01 04:49 UTC
### Is your feature request related to a problem? Please describe.

Please remove the limit of around 1000 songs for new playlists added to the bot's queue.

### What is your ideal solution to the problem?

Remove the limit altogether or set it much higher, like 5-10k songs.

### How would this feature be used?

When using the bot in 24/7 mode as a radio station it's best to have a longer playlist to make it less repetitive, the limit of 1000 songs is a bit restrictive in that regard.

### Additional Info

If changing this globally is not welcome for some reason, a direction on what to change in the code would work too. for those who need/want that change.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-01-31 15:29
Duplicate of #49

**Closed by jagrosh** 2024-01-31 15:29 UTC
