### ISSUE TITLE
[Feature Request] Sponsor block

### ISSUE THREAD

**Issue by NicoaraAlex** [jagrosh/MusicBot#1524] opened 2024-03-24 03:07 UTC
### Is your feature request related to a problem? Please describe.

The request would solve the omission of certain (unnecessary) musical segments according to sponsor block.

### What is your ideal solution to the problem?

The solution would be to integrate the sponsor block plugin from the official website (https://sponsor.ajay.app/).

### How would this feature be used?

The segments should be read from the database and automatically omitted according to the API.

### Additional Info

Sponsorblock integrated would help a lot in the case of many songs, it would be a very good idea to add it.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-03-24 04:01
Duplicate of #982

**Closed by jagrosh** 2024-03-24 04:01 UTC
