### ISSUE TITLE
[Feature Request] Alias Editor

### ISSUE THREAD

**Issue by brockbreacher** [jagrosh/MusicBot#253] opened 2019-07-30 00:21 UTC
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
An alias editor for commands (either in a config file or through discord)

*Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Set something '...'
2. Run some command '...'
3. Other steps or related info '...'
4. ...
If discord based: [p]addalias <maincmd> <alias> e.x l!addalias play p
If config based:
\\Aliases
Play: p

**Additional context**
N/A

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
yes

**Comment by jagrosh** [comment] 2019-07-31 15:58
Closing as this is a duplicate of #213

**Closed by jagrosh** 2019-07-31 15:58 UTC
