### ISSUE TITLE
[Bug Report] The bot does not play songs

### ISSUE THREAD

**Issue by MegaNoam** [jagrosh/MusicBot#389] opened 2020-04-10 18:10 UTC
**Describe the bug**
Once a song is selected in the bot, it enters and exits and does not play the song

**To Reproduce**
!!play https://www.youtube.com/watch?v=k30tMU5XdTw
!!play https://youtu.be/k30tMU5XdTw

**Debug Info**
```
System Properties:
  java.version = 1.8.0_232
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_232-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.7
  Owner = {Censored}
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.34

Runtime Information:
  Total Memory = 64
  Used Memory = 54

Discord Information:
  ID = {Censored}
  Guilds = {Censored}
  Users = {Censored}
```

**Additional context**
```
[20:02:50] [ERROR] [LocalAudioTrackExecutor]: Error in playback of obUHDyWFMi8
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Received non-success response code 404
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
... 4 common frames omitted
```

**Comment by jagrosh** [comment] 2020-04-10 18:15
Duplicate of #370

**Closed by jagrosh** 2020-04-10 18:15 UTC
