### ISSUE TITLE
[Bug Report] Lavaplayer crashes with certain YouTube tracks.

### ISSUE THREAD

**Issue by VeryLongNicknameSuchWow** [jagrosh/MusicBot#594] opened 2021-02-05 14:09 UTC
**Describe the bug**
Bot quickly joins and disconnects from the voice channel and an exception is thrown in the logs. This is probably because the said song is age restricted. From my testing it looks like bumping com.sedmelluq.lavaplayer version to 1.3.66 fixes this problem.

**To Reproduce**
1. Play https://www.youtube.com/watch?v=iJ4IX-E9240

**Logs**
```
[13:58:00] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of iJ4IX-E9240


com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Track information is unavailable.


	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackBaseInfoFromEmbedPage(DefaultYoutubeTrackDetailsLoader.java:199)


	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:83)


	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:54)


	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:40)


	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)


	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)


	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)


	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)


	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)


	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)


	at java.base/java.lang.Thread.run(Thread.java:834)


Caused by: java.lang.IllegalStateException: Expected player config is not present in embed page.


	... 11 common frames omitted
```

**Debug Info**
```
System Properties:
  java.version = 11.0.9
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.9+11-Ubuntu-0ubuntu1
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.2
  Owner = 293374680784699393
  Prefix = .
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = true
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_214
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.55

Runtime Information:
  Total Memory = 31
  Used Memory = 17

Discord Information:
  ID = 349963290379550722
  Guilds = 5
  Users = 4
```

**Comment by emunand** [comment] 2021-02-06 22:44
do you mind showing how to run the bot with the new version?

**Comment by jagrosh** [comment] 2021-02-06 22:46
Duplicate of #574, this will be fixed in the next release

**Closed by jagrosh** 2021-02-06 22:46 UTC
