### ISSUE TITLE
[Bug Report] Discord Bot 404 Error when playing certain song

### ISSUE THREAD

**Issue by YTRemRem** [jagrosh/MusicBot#380] opened 2020-04-09 07:20 UTC
**Describe the bug**
When trying to play a song on YouTube it return a 404 error but it can be played normally when using the web.

**To Reproduce**
@bot play https://www.youtube.com/watch?v=ZTjhcl_733s

**Expected behavior**
play the song normally

**Debug Info**
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/4454621/debug_information.txt)

**Comment by Wqrld** [comment] 2020-04-09 09:06
can reproduce

**Comment by TheCoolOne123** [comment] 2020-04-09 09:07
Can reproduce

**Comment by danny6167** [comment] 2020-04-09 09:10
Same here. Trace from console below.

`[08:55:48] [ERROR] [LocalAudioTrackExecutor]: Error in playback of L_jWHffIx5E
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Received non-success response code 404
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
... 4 common frames omitted`

**Comment by Misat11** [comment] 2020-04-09 09:31
I have same issues for many official songs (any other things are working)

**Comment by danny6167** [comment] 2020-04-09 09:33
Bumping lavaplayer to 1.3.46 and rebuilding seems to have resolved the issue for me.

**Comment by danny6167** [comment] 2020-04-09 09:53
Already resolved by the bump to lavaplayer 1.3.38 in this commit. There just isn't a build posted for it.
https://github.com/jagrosh/MusicBot/commit/61d4c51276a77b83b93fd8b4b9f4ec3570d45a0d

**Comment by iNaruse** [comment] 2020-04-09 10:57
@danny6167 How do you do "Bumping lavaplayer to 1.3.46"?

**Comment by Sattishh** [comment] 2020-04-09 11:01
From the pom file, you need to change the version and then deploy it as .jar file
Alternatively, you can join the discord server where in #support channel, someone added a link to download the .jar file which has the upgraded lavaplayer.

**Comment by iNaruse** [comment] 2020-04-09 11:57
I changed lavaplayer to 1.3.46 but I keep getting the error.

**Comment by jagrosh** [comment] 2020-04-09 12:34
Duplicate of #370

**Closed by jagrosh** 2020-04-09 12:34 UTC
