### ISSUE TITLE
[Feature Request] disconect on empty channel

### ISSUE THREAD

**Issue by ihastunes** [jagrosh/MusicBot#268] opened 2019-09-06 17:59 UTC
**Is your feature request related to a problem? Please describe.**
bandwidth usage

**Describe the solution you'd like**
detect when no one is in the channel after a song finishes playing (queue doesn't have to be empty) and the bot will leave voice and optionally clear queue

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Set something 'possible to set up in config'
2. Run some command 'would probably still end up editing the config'
3. Other steps or related info 'easiest thing to think of is when the current song ends detect who is in voice if lobby == jmusicbot then .disconnect'
4.  profit???

**Additional context**
annoyed with the bot staying in channel when someone queues 700+ songs.

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
yes

**Comment by jagrosh** [comment] 2019-09-30 18:21
Duplicate of [https://github.com/jagrosh/MusicBot/projects/1#card-4483529](an existing planned feature)

**Closed by jagrosh** 2019-09-30 18:21 UTC
