### ISSUE TITLE
Linux host cannot play any songs

### ISSUE THREAD

**Issue by am714** [jagrosh/MusicBot#185] opened 2018-09-29 19:20 UTC
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [ ] I have read through the [planned and suggested features][features]

### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description

When trying to play any kind of things on a linux machine i get the following error:

Exception in thread "lava-daemon-pool-playback-1-thread-4" java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1538248008126/libconnector.so: libstdc++.so.6: cannot open shared object file: No such file or directory

i checked in the jar file and libconnector.so is there so i have no clue why it won't work on linux

**Comment by ExotiCMods** [comment] 2018-10-27 20:31
I have now 4 Bots running on a Linux based server. I installed `openjdk-8-jre-headless`, i then ran the command `nohup java -jar JMusicBot-0.1.3-Linux.jar &` as the & symbol, switches the program to run in the background. With these, I was able to play music instantly. Try this, and I hope it'll work.

**Comment by jagrosh** [comment] 2018-10-29 13:37
I would recommend against using OpenJDK with this bot; it _might_ work, but the jars are compiled for the Oracle JDK. Also @am714, which jar are you using, which java version are you using, and what system/os are you running this on?

**Comment by am714** [comment] 2018-10-29 13:52
I am using oracle java(1.8.0_181) on a 64 bit Ubuntu Server(16.04) tried both with Linux only jar and All-OS(both manually compiled)

**Comment by jagrosh** [comment] 2018-10-29 13:55
How are you running it? Also, have you checked the folder `/tmp/lava-jni-natives/1538248008126/` (on your system, not in the jar) for the libconnector.so? It should get transferred to there if it isn't there when the jar is run.

**Comment by am714** [comment] 2018-10-29 14:00
I can't see the file there, i think it is a problem with my system? I will try manually copy and see what happens

**Comment by am714** [comment] 2018-10-29 14:14
Ugh can't see to get it working... maybe it's a permission related thing. Isn't there anyway in the source code where to tell the bot to go look for that file at a defined location?

**Comment by jagrosh** [comment] 2018-10-29 14:48
No; the underlying library lavaplayer uses those natives. You might be able to recompile that library to suit your needs, but I would guess that running the jar as root (once) might place them in the correct spot and then from then on running as root wouldn't be needed.

**Comment by taking** [comment] 2018-12-06 14:23
I have the same issue.

Centos 7 / Oracle JDK 7

`[14:20:00] [INFO] [WebSocketClient]: Connected to WebSocket
[14:20:01] [INFO] [JDA]: Finished Loading!
[14:20:14] [ERROR] [LocalAudioTrackExecutor]: Error in playback of 2vjPBrBU-TM
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1544106014129/libconnector.so: /tmp/lava-jni-natives/1544106014129/libconnector.so: 동적오브젝트의 세그먼트를 매핑하는 실패: 명령을 허용하지 않음
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77)
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:16)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:14)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:21)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:190)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:174)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:91)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:257)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:75)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        ... 4 common frames omitted
Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1544106014129/libconnector.so: /tmp/lava-jni-natives/1544106014129/libconnector.so: 동적 오브젝트의 세그먼트를 매핑하는 실패: 명령을 허용하지 않음
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77)
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:16)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:14)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:21)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:190)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:174)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:91)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:257)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:75)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[14:20:15] [ERROR] [LocalAudioTrackExecutor]: Error in playback of 2vjPBrBU-TM
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1544106014129/libconnector.so: /tmp/lava-jni-natives/1544106014129/libconnector.so: 동적오브젝트의 세그먼트를 매핑하는 실패: 명령을 허용하지 않음
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)`

**Comment by jagrosh** [comment] 2018-12-06 14:55
Your screenshot shows that you are using OpenJDK; try with oracle JDK and make sure that the jar has permission to write natives to `/tmp/lava-jni-natives/1544106014129/`

**Comment by taking** [comment] 2018-12-07 06:57
@jagrosh 

I am having problems with oracle java.
https://asciinema.org/a/iXDWYk1tewWtve47PGd29e5MR

**Comment by jagrosh** [comment] 2018-12-07 07:00
Can you try deleting the entire lava-jni-natives folder and trying again

**Comment by alfonsojon** [comment] 2018-12-13 09:58
Try emptying your `/tmp` folder and see if that resolves it.

#196

**Comment by jagrosh** [comment] 2019-01-25 19:33
Closing as the aforementioned issue (#196) is the more-general version of this.

**Closed by jagrosh** 2019-01-25 19:33 UTC
Labels: lavaplayer
