### ISSUE TITLE
[Bug Report] Cannot play youtube music links anymore.

### ISSUE THREAD

**Issue by xFanexx** [jagrosh/MusicBot#1623] opened 2024-07-22 01:24 UTC
### Bug Description

Trying to play a youtube link or a song by name will not play it. 
Bot says: "Error loading: Sign in to confirm you’re not a bot".
![Screenshot 2024-07-22 031945](https://github.com/user-attachments/assets/2525af65-c30f-4adc-bea9-ce031a3d7554)

Console Log:
2024-07-22 03:16:32 [01:16:32] [INFO] [JMusicBot]: Loaded config from /jmb/config.txt
2024-07-22 03:16:32 [01:16:32] [INFO] [Settings]: serversettings.json loaded from /jmb/serversettings.json
2024-07-22 03:16:34 [01:16:34] [ERROR] [JMusicBot]: Could not start GUI. If you are running on a server or in a location where you cannot display a window, please run in nogui mode using the -Dnogui=true flag.
2024-07-22 03:16:35 [01:16:35] [INFO] [JDA]: Login Successful!
2024-07-22 03:16:36 [01:16:36] [INFO] [WebSocketClient]: Connected to WebSocket
2024-07-22 03:16:36 [01:16:36] [INFO] [JMusicBot]: JMusicBot
2024-07-22 03:16:36 [01:16:36] [INFO] [JDA]: Finished Loading!
2024-07-22 03:18:18 [01:18:18] [ERROR] [AudioHandler]: Track U4mADkt6o-M has failed to play
2024-07-22 03:18:18 com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Sign in to confirm you’re not a bot
2024-07-22 03:18:18     at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
2024-07-22 03:18:18     at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
2024-07-22 03:18:18     at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
2024-07-22 03:18:18     at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
2024-07-22 03:18:18     at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
2024-07-22 03:18:18     at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
2024-07-22 03:18:18     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
2024-07-22 03:18:18     at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
2024-07-22 03:18:18     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024-07-22 03:18:18     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024-07-22 03:18:18     at java.base/java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

Try to play something via a datacenter IP Address

### Expected Result

Bot should play the music fine but isnt playing it.

### Debug Output

Bot Running at a Windows Server 2022 dedicated server on Docker Desktop. Newest Version 0.4.2.
Newest Java versions.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.2

**Comment by MichailiK** [comment] 2024-07-22 06:26
Duplicate of #1588

**Closed by MichailiK** 2024-07-22 06:26 UTC
