### ISSUE TITLE
[Bug Report] youtube not loading 

### ISSUE THREAD

**Issue by Koreyexpress2s** [jagrosh/MusicBot#1546] opened 2024-04-12 20:39 UTC
### Bug Description

youtube is not supported 

### Steps to Reproduce

nothing work with youtube 

### Expected Result

not loading
![Screenshot 2024-04-12 162006](https://github.com/jagrosh/MusicBot/assets/166870344/2f5ca0af-d4d4-4f5e-bdc2-f16bd5b6ac99)

### Debug Output

win 11 

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-04-12 21:09
Duplicate of existing issues; please check the issue list before reporting.

**Closed by jagrosh** 2024-04-12 21:09 UTC
