### ISSUE TITLE
[Bug Report] People can't use DJ commands when dj set to @everyone

### ISSUE THREAD

**Issue by Seflyx** [jagrosh/MusicBot#301] opened 2019-10-19 15:58 UTC
**Describe the bug**
Basically people can't use DJ commands if I set the DJ roles to everyone.
Since this is used on my private server and there's no need to vote skip or stuff, I tried setting DJ group to everyone. The only workaround for now is putting everyone in temporary created group and set the group as DJ.

**To Reproduce**
1. Admin use '!setdj everyone'
2. Some person use DJ command like '!play' on paused music

**Expected behavior**
Everyone can use DJ commands

**Screenshots**
![image](https://user-images.githubusercontent.com/1592579/67147764-13b95100-f2c2-11e9-8fb5-2c3888e6810f.png)

**Version Info (please complete the following information):**
 - Operating System: Ubuntu 18.04.3
 - JMusicBot Version: 0.2.5

**Comment by Sanduhr32** [comment] 2019-10-19 16:00
I believe the role is called `@everyone` and that it doesnt search for a role. I might be wrong tho.

**Comment by Seflyx** [comment] 2019-10-19 16:08
> I believe the role is called `@everyone` and that it doesnt search for a role. I might be wrong tho.

It search for the role. The id in the config file is the same as the @everyone id.
For example:
![image](https://user-images.githubusercontent.com/1592579/67148077-54ff3000-f2c5-11e9-83fd-450185174c91.png)

**Comment by jagrosh** [comment] 2019-10-19 16:12
The role exists, but technically nobody has the `@ everyone` role, it is just used as the base permissions set. I'll need to explicitly check for this.

**Comment by jagrosh** [comment] 2019-10-21 04:50
So... I'm looking through the source and it turns out [I actually _do_ check for this already](https://github.com/jagrosh/MusicBot/blob/master/src/main/java/com/jagrosh/jmusicbot/commands/DJCommand.java#L42). Therefore, DJ-level commands should work perfectly fine (I'm guessing you'd be able to reproduce this; try setting @ everyone to DJ and see if people can run `pause` or `stop`).

The bug here is that I didn't replicate those identical checks into the `play` command (as it is a normal command, just with DJ-specific behavior if the player is paused). I'll fix this in the next release.

**Comment by jagrosh** [comment] 2019-11-12 16:09
This should be fixed as of 0.2.6

**Closed by jagrosh** 2019-11-12 16:09 UTC
Labels: bug
