### ISSUE TITLE
[Bug Report] not playing song via youtube but will play songs from soundcloud and others 

### ISSUE THREAD

**Issue by ggnoods** [jagrosh/MusicBot#1704] opened 2024-10-03 15:06 UTC
### Bug Description

when i run the command i get an error and no sound from the bot or even the song going into the q. 
![image](https://github.com/user-attachments/assets/d405c679-4cf3-4b8c-bf45-c43e1f7f8727)

as you can see from the pic this is the error hope anyone can giveme a run down on what i need to do for a fix or even if i could fix it at all 

### Steps to Reproduce

1. have a bot in a server 
2. run it's command for a youtube song for the one i did it was playing god 
3. watch lol 

### Expected Result

for the bot to play the song but no song. 

### Debug Output

[debug_information.txt](https://github.com/user-attachments/files/17246219/debug_information.txt)

### Additional Info

might be a lava player bug again 

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

the jar file is 0.4.3

**Comment by MichailiK** [comment] 2024-10-03 16:03
Duplicate of #1682

**Closed as not planned by MichailiK** 2024-10-03 16:03 UTC
