### ISSUE TITLE
[Bug Report] ERR when try to play a youtube song 

### ISSUE THREAD

**Issue by NicoaraAlex** [jagrosh/MusicBot#1784] opened 2024-12-12 15:34 UTC
### Bug Description

It shows me an error in the console, looking for more details it's about Lavalink.

### Steps to Reproduce

1. run .jar
2. play a song

### Expected Result

to sing the song

### Debug Output

System Properties:
  java.version = 11.0.25
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.25+9
  java.specification.version = 11
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.3
  Owner = 436555573484322827
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 512
  Used Memory = 122

Discord Information:
  ID = 1256292172320477184
  Guilds = 3
  Users = 3

### Additional Info

[17:30:30] [INFO] [JMusicBot]: Loaded config from C:\Users\user\Desktop\musicbot\config.txt
[17:30:31] [INFO] [JDA]: Login Successful!
[17:30:31] [INFO] [WebSocketClient]: Connected to WebSocket
[17:30:31] [INFO] [JDA]: Finished Loading!
[17:30:52] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/5b77d519/player_ias.vflset/ro_RO/base.js detected (issue detected with script: no actions match). Dumped to C:\Users\user\AppData\Local\Temp\lavaplayer-yt-player-script10782541872614137386.js
[17:30:52] [WARN] [DefaultAudioPlayerManager]: Suspicious exception for loading item https://youtu.be/ekr2nIex040?si=qAfW1qDN_myNR7Mr
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video cannot be loaded.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at dev.lavalink.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:198)
	at dev.lavalink.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:147)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:442)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:423)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:154)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:167)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItemOrdered$1(DefaultAudioPlayerManager.java:196)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:90)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Must find action functions from script: /s/player/5b77d519/player_ias.vflset/ro_RO/base.js
	at dev.lavalink.youtube.cipher.SignatureCipherManager.extractFromScript(SignatureCipherManager.java:235)
	at dev.lavalink.youtube.cipher.SignatureCipherManager.getCipherScript(SignatureCipherManager.java:195)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadVideo(NonMusicClient.java:318)
	at dev.lavalink.youtube.YoutubeAudioSourceManager.lambda$routeFromVideoId$6(YoutubeAudioSourceManager.java:305)
	at dev.lavalink.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:181)
	... 12 common frames omitted

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment] 2024-12-12 16:54
Duplicate of #1783

**Closed as not planned by MichailiK** 2024-12-12 16:54 UTC
