### ISSUE TITLE
JMusicBot Dead

### ISSUE THREAD

**Issue by Seabass-ui** [jagrosh/MusicBot#1740] opened 2024-10-25 22:45 UTC
### Bug Description

No update from the author for several days. A forked version was released and is dead now. Will there be an update soon?

### Steps to Reproduce

1. Some transparency would be nice, just tell us you've abandoned the project?

### Expected Result

The thingy to play music in my other thingy...

### Debug Output

I'm on the forked 4.3.1 version submitted by some other user here. this version has been working until the other day. 

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

4.3.1

**Comment by MichailiK** [comment] 2024-10-26 00:26
The forks are based off this PR:

- #1670

This PR & [a separate PR for the wiki](https://github.com/jagrosh/MusicBot/pull/1714) require some finishing touches & thus are still work in progress. We plan to release 0.4.4 as soon as these two PRs are ready and merged.

I'm going to close this issue as it seems to effectively be a duplicate of #1588. Subscribe to that issue to receive updates regarding this issue.

**Closed as not planned by MichailiK** 2024-10-26 00:26 UTC
