### ISSUE TITLE
[Feature Request] Media Operation Button

### ISSUE THREAD

**Issue by Lapius7** [jagrosh/MusicBot#1647] opened 2024-08-05 11:49 UTC
### Is your feature request related to a problem? Please describe.

When using the「{prefix}nowplaying」command, please enable the reaction buttons to "pause, resume, skip 10 seconds, go back 10 seconds, go to the next song, go to the previous song," etc.

### What is your ideal solution to the problem?

Please add reaction button function.

### How would this feature be used?

pause
resume
skip 10 seconds
go back 10 seconds
go to the next song
go to the previous song

### Additional Info

As an example, I created an image as shown below.
![Media_operation_button-MusicBotIdea](https://github.com/user-attachments/assets/8520eacd-563d-442e-bdcb-84a4f91263c7)

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-08-05 19:56
Duplicate of #194

**Closed by jagrosh** 2024-08-05 19:56 UTC
