### ISSUE TITLE
[Feature Request] Custom Language

### ISSUE THREAD

**Issue by kakagesicht2** [jagrosh/MusicBot#321] opened 2019-11-15 23:25 UTC
I would really like to see a language file, which gives the possibility to change the messages of the bot in your language.

**Comment by jagrosh** [comment] 2019-11-16 00:45
Duplicate of [existing in-progress feature](https://github.com/jagrosh/MusicBot/projects/1#card-3994842)

**Closed by jagrosh** 2019-11-16 00:45 UTC
