### ISSUE TITLE
[Feature Request] Help With Embed.

### ISSUE THREAD

**Issue by Mu7aMNaD** [jagrosh/MusicBot#457] opened 2020-07-05 18:21 UTC
options for every command if i type #help play it shows me the in embed.
my English is bad so here is a photo so you can understand me better.

![photo](https://i.ibb.co/bmy8VbL/download.png)

**Comment by jagrosh** [comment] 2020-07-05 19:57
This seems like a duplicate of #444

**Closed by jagrosh** 2020-07-05 19:57 UTC
