### ISSUE TITLE
[Bug Report] Bot Doesn't listen to certain people and outright fails, but listens to other people

### ISSUE THREAD

**Issue by M1ghtyboyPersonal** [jagrosh/MusicBot#528] opened 2020-10-26 21:18 UTC
**Describe the bug**
The Music bot would heed no search results whenever I and other people try and search for a song, and links just make the bot say "Failed to load song" the bot does join the music channel however only certain people can use the bot

**To Reproduce**
No idea how to reproduce, the console window floods with errors however. I may need to get you in a server with me to demonstrate
**Expected behavior**
The bot plays music no problem

**Screenshots**

![image](https://user-images.githubusercontent.com/29181101/97229627-924ba700-17d0-11eb-93a5-848768ec099e.png)
When the song was added through searching, the console spewed errors and the bot disconnected

**Debug Info**
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/5441615/debug_information.txt)

**Additional context**
worked fine at first, resetting the bot will probably fix it

**Comment by MichailiK** [comment] 2020-10-26 21:19
Very likely related to #520

**Comment by jagrosh** [comment] 2020-10-26 21:22
Dupe of #520

**Closed by jagrosh** 2020-10-26 21:22 UTC
