### ISSUE TITLE
youtube not work again 

### ISSUE THREAD

**Issue by H1LL** [jagrosh/MusicBot#1695] opened 2024-09-25 16:22 UTC
### Bug Description

youtube script stop 

### Steps to Reproduce

afaf

### Expected Result

afa

### Debug Output

faf

### Additional Info

faf

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

4.3

**Comment by MichailiK** [comment] 2024-09-25 16:24
Duplicate of #1694

**Closed as not planned by MichailiK** 2024-09-25 16:24 UTC
