### ISSUE TITLE
[Feature Request] Search/Queue local files

### ISSUE THREAD

**Issue by ui5140** [jagrosh/MusicBot#708] opened 2021-05-31 14:48 UTC
**Is your feature request related to a problem? Please describe.**
There is no option go queue/search from local library(playlist)

**Describe the solution you'd like**
Add a command to search from the local library/playlist and add it to the queue list

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. For example, I want to listen to "Brain Power.mp3", which is also 5th song in my Playlist "exciting.txt"
2. I use either commands like "!localqueue Brain Power" or "!localqueue exciting 5", and the bot adds the song next to the queue

**Additional context**
The search/queue function only works for online resources, but I only use this bot for local files.

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

**Comment by jagrosh** [comment] 2021-05-31 17:21
Duplicate of #404

**Closed by jagrosh** 2021-05-31 17:21 UTC

**Comment by ui5140** [comment] 2021-05-31 19:36
Hi,
I read the 404 thread and your concern for the issue. Wouldnt my second suggestion of playing nth song from x playlist work without the issue? It would essentially be like using "play playlist x", "skipto n" but more simple and not have to add other songs into the list.
