### ISSUE TITLE
[Bug Report] Error in loading item. Loading information for a Youtube track failed.

### ISSUE THREAD

**Issue by SarenShadow** [jagrosh/MusicBot#591] opened 2021-01-24 21:10 UTC
Upon trying to play a song it's not able to load the song. There's an error in loading item. Loading information for a Youtube track failed.

**To Reproduce**
1. Play a song (;play (song of choosing))

**Expected behavior**
Music loads and plays

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/39988841/105643514-9a2eec00-5e90-11eb-9ca5-e8e822b09c95.png)

**Debug Info**
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/5863190/debug_information.txt)

**Additional context**
This suddenly happened while listening to the bot. Ever since not being able to play music with Youtube. Soundcloud works just fine

**Comment by jagrosh** [comment] 2021-01-24 21:31
Duplicate of #305

**Closed by jagrosh** 2021-01-24 21:31 UTC
