### ISSUE TITLE
[Feature Request] Add / Commands 

### ISSUE THREAD

**Issue by AlexMayne5** [jagrosh/MusicBot#1200] opened 2022-08-17 11:22 UTC
### Is your feature request related to a problem? Please describe.

no

### What is your ideal solution to the problem?

1. Discord wants bots to move to / commands 

### How would this feature be used?

/play would how the usage of the command 

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-08-17 11:36
Duplicate of #664

**Closed by MichailiK** 2022-08-17 11:36 UTC
