### ISSUE TITLE
[Feature Request] Show currently playing Artist and Title from Icecast stream

### ISSUE THREAD

**Issue by ncrqnt** [jagrosh/MusicBot#569] opened 2020-12-06 14:11 UTC
**Is your feature request related to a problem? Please describe.**
Nope, just an new idea.

**Describe the solution you'd like**
When playing an Icecast-stream, instead of just showing "Listening to [Radio/Source Name]" show "Listening to [Artist - Title]".

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Play an Icecast-Stream
2. The bot shows "Listening to [Artist - Title]" as status / current game.
3. You know what song is currently played and by who.

**Additional context**
So far, I only saw this feature in one bot (sinusbot)

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
Yes.

**Comment by jagrosh** [comment] 2021-01-12 18:03
This is effectively a duplicate of #102, as the bot can only show whatever lavaplayer provides

**Closed by jagrosh** 2021-01-12 18:03 UTC
