### ISSUE TITLE
[Bug Report] Error loading track

### ISSUE THREAD

**Issue by REMOOO** [jagrosh/MusicBot#517] opened 2020-10-17 03:41 UTC
**Error loading track**
Mostly when I play a song he gives me [Error loading track].

**Comment by lordbinchicken** [comment] 2020-10-23 19:00
lavaplayer issue, being fixed in the next update, this is a dupe of #515 and several others

**Comment by jagrosh** [comment] 2020-10-23 19:34
Duplicate of #520 (closing this one as it has less info)

**Closed by jagrosh** 2020-10-23 19:34 UTC
