### ISSUE TITLE
[Feature Request] WEE NEED PLS Bass Boost

### ISSUE THREAD

**Issue by HansDerechte** [jagrosh/MusicBot#1464] opened 2023-12-23 00:11 UTC
### Is your feature request related to a problem? Please describe.

Sometimes I miss a little more bass in the songs and so you could just apply it to all songs

### What is your ideal solution to the problem?

A function that has a selectable level of bass to embellish songs

### How would this feature be used?

1.Enter command from the bot 
2.Enter bass boost 
3.Select level 1-150

### Additional Info

I know something like this has been posted before but nothing happens so please add Bass Boost soon, the other Bass Boost post was already 3 years ago!

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by HansDerechte** [comment] 2023-12-23 00:14
Oh sorry

**Comment by MichailiK** [comment] 2023-12-23 05:23
Duplicate of #968

**Closed by MichailiK** 2023-12-23 05:23 UTC
