### ISSUE TITLE
[Bug Report] Failure to Play

### ISSUE THREAD

**Issue by KronosComp** [jagrosh/MusicBot#1720] opened 2024-10-14 00:01 UTC
### Bug Description

When I put in the !play command with a link, the console errors and says it fails to play, but in the server it says its added, but nothing plays and when you check the queue it says nothing is on it. 

### Steps to Reproduce

1. Version 0.4.3
2. Do the !play command with a Youtube video

### Expected Result

For music to play

### Debug Output

System Properties:
  java.version = 17.0.10
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 17.0.10+11-LTS-240
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 11

JMusicBot Information:
  Version = 0.4.3
  Owner = (Deleted By Poster)
  Prefix = !
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 148
  Used Memory = 19

Discord Information:
  ID = (Deleted By Poster)
  Guilds = 1
  Users = 8
```


### Additional Info

_No response_

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by Bykle** [comment] 2024-10-14 09:58
I am seeing similar issues, running version 0.4.3 on Debian 12 Linux Kernel 6.5.11, openjdk 17.0.11 2024-04-16.

```
Oct 14 20:55:12 ecbrdbotp2 java[46304]: [20:55:12] [INFO] [JMusicBot]: Loaded config from /opt/jmusicbot/config.txt
Oct 14 20:55:12 ecbrdbotp2 java[46304]: [20:55:12] [INFO] [Settings]: serversettings.json loaded from /opt/jmusicbot/serversettings.json
Oct 14 20:55:14 ecbrdbotp2 java[46304]: [20:55:14] [INFO] [JDA]: Login Successful!
Oct 14 20:55:15 ecbrdbotp2 java[46304]: [20:55:15] [INFO] [WebSocketClient]: Connected to WebSocket
Oct 14 20:55:15 ecbrdbotp2 java[46304]: [20:55:15] [INFO] [JDA]: Finished Loading!
Oct 14 20:55:18 ecbrdbotp2 java[46304]: [20:55:18] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/2f238d39/player_ias.vflset/en_GB/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script11372491452963680378.js
Oct 14 20:55:20 ecbrdbotp2 java[46304]: [20:55:20] [ERROR] [LocalAudioTrackExecutor]: Error in playback of vMvrRV6v0SM
Oct 14 20:55:20 ecbrdbotp2 java[46304]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.lang.Thread.run(Thread.java:840)
Oct 14 20:55:20 ecbrdbotp2 java[46304]: Caused by: java.lang.RuntimeException: Not success status code: 403
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.io.DataInputStream.readByte(DataInputStream.java:268)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         ... 4 common frames omitted
Oct 14 20:55:20 ecbrdbotp2 java[46304]: [20:55:20] [ERROR] [AudioHandler]: Track vMvrRV6v0SM has failed to play
Oct 14 20:55:20 ecbrdbotp2 java[46304]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.lang.Thread.run(Thread.java:840)
Oct 14 20:55:20 ecbrdbotp2 java[46304]: Caused by: java.lang.RuntimeException: Not success status code: 403
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at java.base/java.io.DataInputStream.readByte(DataInputStream.java:268)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
Oct 14 20:55:20 ecbrdbotp2 java[46304]:         ... 4 common frames omitted
```

**Comment by MichailiK** [comment] 2024-10-14 10:48
Duplicate of #1682

**Closed as not planned by MichailiK** 2024-10-14 10:48 UTC
