### ISSUE TITLE
[Feature Request] Add play-skip command

### ISSUE THREAD

**Issue by MichaelTene7** [jagrosh/MusicBot#1228] opened 2022-10-08 03:20 UTC
### Is your feature request related to a problem? Please describe.

Currently; two separate commands must be used to change the currently playing track: !Play [new track], followed by !Skip 

### What is your ideal solution to the problem?

A single command, which can perform this function. 

### How would this feature be used?

1. !playskip [song] is sent
2. The specified [song] is added to the queue
3. The currently playing song is skipped (without an additional command being sent)

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2022-10-10 13:12
Duplicate of #155

**Closed by jagrosh** 2022-10-10 13:12 UTC
