### ISSUE TITLE
[Bug Report] 403 Response from YouTube

### ISSUE THREAD

**Issue by iamnasv** [jagrosh/MusicBot#1437] opened 2023-09-29 22:49 UTC
### Bug Description

Everytime the track fails to play & will get skipped without any prompt. The following exception will be thrown, indicating JMusicBot received a 403 response from YouTube, every other platform was not affected.

I have restarted the bot, restarted the server and did a fresh install but it keeps happening.

### Steps to Reproduce

use -play https://www.youtube.com/watch?v=dsuJZx24V_A (-play since the prefix was changed from original, and this track used to play without an issue)

### Expected Result

YouTube tracks to load & play without issue

### Debug Output

[22:40:36] [ERROR] [LocalAudioTrackExecutor]: Error in playback of dsuJZx24V_A
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-72-generic
  java.vendor: Eclipse Adoptium
  java.version: 20.0.1
  java.runtime.version: 20.0.1+9
  java.vm.version: 20.0.1+9
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:116)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166)
        at java.base/java.io.DataInputStream.readUnsignedByte(Unknown Source)
        at java.base/java.io.DataInputStream.readByte(Unknown Source)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
        ... 4 common frames omitted

### Additional Info

[#885](https://github.com/jagrosh/MusicBot/issues/885) was marked as resolved but it seems that the issue still persists, please don't merge with that issue.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by pavl21** [comment] 2023-10-03 21:38
I have the same problem

**Comment by busybox11** [comment] 2023-10-12 23:43
same here

**Comment by andy01745** [comment] 2023-10-14 04:09
same

**Comment by ZIFIXLeDebutant** [comment] 2023-11-01 15:17
this problem has also recently appeared and yet everything was fine yesterday

**Comment by mahmud-niaz** [comment] 2023-11-02 19:53
facing the same issue...I need to restart the server everytime when ever this happened. can anyone help me to solve this?

**Comment by PerplexedGator** [comment] 2023-11-28 00:50
Same issue, been like this for a while now.

**Comment by WildChargerTV** [comment] 2024-01-02 06:35
+1. Only happens with one specific video so far for me but definitely a problem.

**Comment by Molenfeuer** [comment] 2024-01-26 23:22
> Can you try another LavaPlayer Library?
> 
> Maven:
> 
> ```
>         <dependency>
>             <groupId>dev.arbjerg</groupId>
>             <artifactId>lavaplayer</artifactId>
>             <version>2.0.2</version>
>         </dependency>
> ```

It works (at least for now)! 
## Linux Guide
1. Just delete or comment out the following block from pom.xml
```
<dependency>
  <groupId>com.github.jagrosh</groupId>
  <artifactId>lavaplayer</artifactId>
  <version>jmusicbot-SNAPSHOT</version> 
</dependency>
```
2. Replace it with @MasqueOu part
```
<dependency>
  <groupId>dev.arbjerg</groupId>
  <artifactId>lavaplayer</artifactId>
  <version>2.0.2</version>
</dependency>
```
3. Install Maven according to [this guide by Digital Ocean](https://www.digitalocean.com/community/tutorials/install-maven-linux-ubuntu)! (Windows and mac have to search their own solution :D But at least WSL should work)
4. Download this MusicBot **sourcecode** and open its folder
5. Run "mvn package"
6. The bot is located under **target/JMusicBot-X.X.X-All.jar**!

**Comment by jagrosh** [comment] 2024-01-26 23:36
Duplicate of #885

**Closed by jagrosh** 2024-01-26 23:36 UTC

**Comment by WildChargerTV** [comment] 2024-01-27 00:47
damn he really did that despite OP lol
