### ISSUE TITLE
[Feature Request] Message Customization

### ISSUE THREAD

**Issue by ClassyCustom** [jagrosh/MusicBot#1279] opened 2023-02-10 02:47 UTC
### Is your feature request related to a problem? Please describe.

Customization of the bots chat messages

### What is your ideal solution to the problem?

Add options to the config allowing personalization of the messages the bot sends 

### How would this feature be used?

type commands see the beautiful custom messages

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2023-02-10 16:22
Once they get implemented, you could use localizations to customize messages, so I will treat this as a duplicate of #689

**Closed by MichailiK** 2023-02-10 16:22 UTC
