### ISSUE TITLE
Problem with linux .service startup

### ISSUE THREAD

**Issue by TheDjRider** [jagrosh/MusicBot#410] opened 2020-05-20 08:10 UTC
Hello, 

When i create subuser and edit the service file my code is:

> [Unit]
Description=EternalRadio Discord Bot
After=network.target

[Service]
WorkingDirectory=/home/eternalradio/
User=eternalradio
Group=eternalradio
ExecStart=nohup java -Dnogui=true -jar JMusic.jar &

RestartSec=15
Restart=always

[Install]
WantedBy=multi-user.target

It start without errors but give:

>  eternalradio.service - EternalRadio Discord Bot
   Loaded: loaded (/lib/systemd/system/eternalradio.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-05-20 11:01:30 EEST; 12s ago
  Process: 5865 ExecStart=/usr/bin/nohup java -Dnogui=true -jar JMusic.jar & (code=exited, status=1/FAILURE)
 Main PID: 5865 (code=exited, status=1/FAILURE)

and also the bot didn't start. If i load it on screen everything is ok but with this future is basically better to have it auto-load on system boot.

Also i have try other way to add startup command into run.sh file and put it into etrnalradio.service but again give the same error.

**Comment by Sanduhr32** [comment] 2020-05-20 13:03
Did it generate a crash log?

**Comment by TheDjRider** [comment] 2020-05-21 17:21
No, nothing but sent in the message above.

**Comment by jagrosh** [comment] 2020-05-30 19:40
I can't really help without more logs, but I'm guessing that the issue is using `nohup ... &` in a service; `nohup` is for terminal use, as it makes a process ignore the 'hangup' of closing the terminal, and `&` is for running in the background, which in theory a service would already be doing. I would recommend trying different variations without `nohup` or `&`. Feel free to re-open this issue if you try those and can produce more logs that might hint at the origin of the issue.

**Closed by jagrosh** 2020-05-30 19:40 UTC

**Comment by pbanj** [comment] 2021-09-16 01:53
if anyone else is having this issue here is my working one. make sure you change username, group, and working directory to your stuff. i was having the same issue and google brought me here @jagrosh was right about removing `nohup` and `&`

`[Unit]
Description=musicbot systemd service unit file.

[Service]
WorkingDirectory=/home/musicbot/musicbot/
User=musicbot
Group=musicbot
ExecStart=java -Dnogui=true -jar JMusicBot.jar

RestartSec=15
Restart=always

[Install]
WantedBy=multi-user.target`


![image](https://user-images.githubusercontent.com/17306233/133536539-a22bd80d-398f-453f-a2bc-793cd64beb42.png)
