### ISSUE TITLE
"Java exception has occurred"

### ISSUE THREAD

**Issue by mikanzil** [jagrosh/MusicBot#1506] opened 2024-03-10 21:08 UTC
### Bug Description

Unable to run the latest (0.4.0) version, have tried with several different versions of Java. Only getting "Java Exception has Occurred" error.

### Steps to Reproduce

1. Download latest version
2. Run .jar (should get error at this point)

### Expected Result

The program should simply launch, but...

### Debug Output

[debug_information.txt](https://github.com/jagrosh/MusicBot/files/14551793/debug_information.txt)

(This is from the last version I'm able to run)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [x] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-03-10 22:18
Duplicate of #1497

**Closed by jagrosh** 2024-03-10 22:18 UTC
