### ISSUE TITLE
Java update causing issues Jbot needs updated

### ISSUE THREAD

**Issue by FreakyBeast** [jagrosh/MusicBot#1748] opened 2024-10-31 11:28 UTC
### Bug Description

I have ran the bot for months and then I installed the new java and boom the bot now just comes in and out of the discord over and over until you give the stop command. Java is the issue here. JBOT needs a update.

### Steps to Reproduce

All i did was install the java and the bot now when played comes in and out of the channel until you give the stop command.

### Expected Result

Jbot needs an update after the new java update please. 

### Debug Output

```
System Properties:
  java.version = 23.0.1
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 23
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 23.0.1+11-39
  java.specification.version = 23
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.3
  Owner = 375179014035472384
  Prefix = !
  AltPrefix = /
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 88
  Used Memory = 44

Discord Information:
  ID = 1006444813631111188
  Guilds = 2
  Users = 2
```

### Additional Info

The issue is that Jbot needs an update and until the author updates it is unusable.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment] 2024-10-31 12:13
YouTube has recently made changes causing **all** JMusicBot versions to break, it has nothing to do with the Java update. We are already tracking those issues here:

- #1588
- #1682

I'm going to close this issue as this is likely a duplicate of the two issues above.

**Closed as not planned by MichailiK** 2024-10-31 12:13 UTC
