### ISSUE TITLE
[Feature Request] Seek command

### ISSUE THREAD

**Issue by iCrazyBlaze** [jagrosh/MusicBot#830] opened 2021-09-16 19:49 UTC
# The problem
I've recently set up the bot on heroku and have been enjoying the experience so far, however the lack of a seek command when playing larger playlists that are compiled into one video makes it basically impossible to find the part you want.
![example](https://i.imgur.com/TH74aXk.png)

The only way to solve this problem currently is to find an alternative that's in playlist form, but that's not always an option and it's much less effort to just type the name of the soundtrack you want to play.
# An alternative solution
Rather than a seek command, the bot could split YouTube videos with chapters into individual "songs" in the queue. It would probably be best to implement a seek command too however, for choosing what part of a longer song you want to listen to.

Thanks for making this bot, it's been great! By the way, I have the deployment scripts for heroku on my GitHub profile.

**Comment by MichailiK** [comment] 2021-09-16 19:50
Duplicate of #469

**Closed by MichailiK** 2021-09-16 19:50 UTC

**Comment by jagrosh** [comment] 2021-09-16 21:40
Please do not use heroku to run this bot, as they don't provide adequate file storage access.
