### ISSUE TITLE
[WARN] [ExceptionTools]: no PLAYER_JS_URL in youtube root EID

### ISSUE THREAD

**Issue by BjornLV** [jagrosh/MusicBot#660] opened 2021-04-01 22:19 UTC
So I got this error whenever I try to play a song from youtube, if I play for instance a song from my website database it seems to work just fine.

[00:06:11] [INFO] [Startup]: Loaded config from \...\config.txt
[00:06:12] [INFO] [JDA]: Login Successful!
[00:06:12] [INFO] [WebSocketClient]: Connected to WebSocket
[00:06:13] [INFO] [JDA]: Finished Loading!
[00:06:16] [WARN] [ExceptionTools]: no PLAYER_JS_URL in youtube root EID: ...(9 lines error)

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/

Well, hope this can be fixed soon...

**Comment by MichailiK** [comment] 2021-04-01 23:01
Duplicate of #658

**Closed** 2021-04-01 23:01 UTC
