### ISSUE TITLE
[Bug Report] RateLimiter encountered 429

### ISSUE THREAD

**Issue by RyanL-29** [jagrosh/MusicBot#421] opened 2020-05-29 04:14 UTC
**Describe the bug**
This bug suddenly happen on last night. The console shwoing out

I can't solve it. I trying to recreate the text channel, voice channel, restart the bot. re-download the bot. 
This problem will causing some song can't play. It will just showing this warning and skip my song until it found a song can play.
**To Reproduce**
I am not sure how to reproduce it... But you can have a try to let it run in a server about 3 weeks non-stop than this error may having chance to happen.

**Screenshots**
https://imgur.com/a/Bd4bP94

**Debug Info**
JMuiscBot: ver. 0.2.8
Operating system: Windows 10 Pro ver.1909 build 18363.836
java version "1.8.0_251"
java SE runtime environment (build 1.8.0_251-b08)
java HotSpot 64-bit Server VM (build 25.251-b08, mixed mode)

**Comment by jagrosh** [comment] 2020-05-29 04:17
Duplicate of #305

**Closed by jagrosh** 2020-05-29 04:17 UTC
