### ISSUE TITLE
[Bug Report] Bot joins then leaves

### ISSUE THREAD

**Issue by AlexMayne5** [jagrosh/MusicBot#553] opened 2020-11-02 20:56 UTC
**Describe the bug**
The bot will join and then leave while not playing anything 

**To Reproduce**
1. play a song (only some songs do this EG: ?play red like roses
2. look at the msg that bot sent ( Added Red Like Roses (Red Trailer) (feat. Casey Lee Williams) (03:12) to begin playing)
3. bot will join 
4. bot will fail and leave 

**Expected behavior**
play song with no problem

**Screenshots**
![image](https://user-images.githubusercontent.com/46424598/97918977-e9142c00-1d4e-11eb-89b1-4e60eb446f00.png)

**Debug Info**
System Properties:
  java.version = 14.0.1
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 14
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 14.0.1+7
  java.specification.version = 14
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.3.1
  Owner = 278923567973007362
  Prefix = ?
  AltPrefix = @mention
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_212
  JDA-Utilities Version = 3.0.4
  Lavaplayer Version = 1.3.59

Runtime Information:
  Total Memory = 50
  Used Memory = 31

Discord Information:
  ID = 535166675872514049
  Guilds = 16
  Users = 2

**Comment by jagrosh** [comment] 2020-11-02 21:05
Duplicate of #531

**Closed by jagrosh** 2020-11-02 21:05 UTC
