### ISSUE TITLE
[Feature Request] Play music while having the client audio off

### ISSUE THREAD

**Issue by pernodpepper** [jagrosh/MusicBot#909] opened 2021-09-24 12:03 UTC
### Is your feature request related to a problem? Please describe.

I cannot play music while the audio for my client is off. We have a setup where one discord account is the music player and the other users then can control the setup.

### What is your ideal solution to the problem?

Can there be a switch in the config for those kind of options.

### How would this feature be used?

1. I join the channel while having the audio off
2. I am able to use the play command without turning my speakers on

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2021-09-27 18:42
Duplicate of #684

**Closed by jagrosh** 2021-09-27 18:42 UTC
