### ISSUE TITLE
[Feature request] Adding spotify support and skipping song that the user not in the voice channel

### ISSUE THREAD

**Issue by RyanL-29** [jagrosh/MusicBot#401] opened 2020-04-26 15:11 UTC
Now the bots only supoort soudcloud and youtube.Can adding spotify can be a source of playing music. I knwo that straming from spotify is impossible. But if the user input the soptify then it will automatically scan the song name of the link and find it on youtube. Adding to lthe list. Hope this feature can add. 

Also, many ofthe user always add thier into the playlist and left. So can add a fucntion that will skip the song that the player not in the channel. Just adding this feature can turn on and off in the config file. Thanks

**Comment by jagrosh** [comment] 2020-04-26 17:31
Duplicate of #392

**Closed by jagrosh** 2020-04-26 17:31 UTC
