### ISSUE TITLE
[Feature Request] Use of "/" commands

### ISSUE THREAD

**Issue by RobsonTigerPl** [jagrosh/MusicBot#1683] opened 2024-09-08 07:04 UTC
### Is your feature request related to a problem? Please describe.

No it's not related to a problem.

### What is your ideal solution to the problem?

My solution to the problem is that users can use "/" command rather than prefixes.

### How would this feature be used?

1. User hit "/" on keyboard and see all commands, or use Apps & Commands button.
2. User see bot commands with descriptions.
3. User choose command by typing it or clicking on it.

### Additional Info

Bot would be easier to use.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2024-09-08 09:00
Duplicate of #664

**Closed as not planned by MichailiK** 2024-09-08 09:00 UTC
