### ISSUE TITLE
[Bug Report] 💡 All entries in this playlist were longer than the allowed maximum (00:00)

### ISSUE THREAD

**Issue by Leavaris** [jagrosh/MusicBot#1145] opened 2022-04-05 23:38 UTC
### Bug Description

0.3.7 solved this issue with YT not playing back (single song), but trying to load up a YT playlist still errors
"💡 All entries in this playlist were longer than the allowed maximum (00:00)"

Seems like a separate issue but this began happening at the same time as the YT play back error that prompted 0.3.7 fix. Changing the config time length has no effect

### Steps to Reproduce

que up any yt playlist (not individual song) example : (>> being my bots prefix)
>>play https://www.youtube.com/playlist?list=PLw2HgxPxeoFRP5_3hFZfTd_yh0CF6KjAK

returns:
💡 All entries in this playlist were longer than the allowed maximum (00:00)

### Expected Result

YT playlist queing worked fine until todays other YT issue.

### Debug Output

System Properties:
  java.version = 11.0.7
  java.vm.name = OpenJDK Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.7+10-post-Raspbian-3deb10u1
  java.specification.version = 11
  os.arch = arm
  os.name = Linux

JMusicBot Information:
  Version = 0.3.7
  Owner = 85318783345913856
  Prefix = >>
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.3.0_324
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 66
  Used Memory = 33

Discord Information:
  ID = 937538375622226000
  Guilds = 1
  Users = 6

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2022-04-05 23:41
There are two problems here:
1. The playlist is failing to load any entries
2. The error message doesn't account for a possible empty playlist

**Comment by Leavaris** [comment] 2022-04-05 23:46
the playlist works fine and is not empty,, its the same play list we have been using for months. additionally no other playlists will load, they all display the same error

**Comment by jagrosh** [comment] 2022-04-05 23:47
I know the playlist isn't empty, youtube made a change today

**Comment by WXPP21** [comment] 2022-04-06 01:39
When will YouTube solve this problem?

**Comment by SpielenmitLili** [comment] 2022-04-06 17:26
I hope that you will get this problem fixed and that we will soon be able to use the bot again as usual.

**Comment by CptnFlipFlops** [comment] 2022-04-06 18:29
We have the **same issue** :
![image](https://user-images.githubusercontent.com/39991183/162043054-51048e1f-8c70-4237-ae99-d0ab9e22063e.png)
(Frisky is just the name, under the hood its MusicBot

**Comment by AntonMacG** [comment] 2022-04-06 18:40
> We have the **same issue** : ![image](https://user-images.githubusercontent.com/39991183/162043054-51048e1f-8c70-4237-ae99-d0ab9e22063e.png) (Frisky is just the name, under the hood its MusicBot)

Everyone has the same issue when loading playlists rn, its a pain to debug but there will be a patch when one is found I'm sure

**Comment by jagrosh** [comment] 2022-04-06 19:23
There's no need to post more screenshots, all playlists are broken and will display this (incorrect) error message.

**Comment by MichailiK** [comment] 2022-04-06 20:04
I have found the cause of this bug & [made a fix](https://github.com/jagrosh/lavaplayer/pull/2). A new version of JMusicBot containing this fix should release soon.

**Comment by Mister-42** [comment] 2022-04-06 20:42
> I have found the cause of this bug & [made a fix](https://github.com/jagrosh/lavaplayer/pull/2). A new version of JMusicBot containing this fix should release soon.

That's awesome, thank you very much for all your efforts.

**Comment by CavanDuck** [comment] 2022-04-06 21:39
Thanks, will look out for update.

**Comment by jagrosh** [comment] 2022-04-06 22:39
Fixed as of v0.3.8

**Closed by jagrosh** 2022-04-06 22:39 UTC
Labels: bug

**Comment by Leavaris** [comment] 2022-04-06 23:59
> Fixed as of v0.3.8

Amazing! TY for your hard work, this bots awesome and my community loves it!
