### ISSUE TITLE
[Bug Report] Music videos depicting "Suicide or Self Harm" cannot be played

### ISSUE THREAD

**Issue by AnOddName** [jagrosh/MusicBot#1162] opened 2022-04-24 23:15 UTC
### Bug Description

A friend of mine on a server tried to play this track:

 https://www.youtube.com/watch?v=zOujzvtwZ6M

and it didn't play.

Other songs/playlists are played without issue.

### Steps to Reproduce

1 - Try and play aforementioned track (Songs/playlists otherwise are played.)

2 - Bot will reply with 

> 🎶 Added Lil Peep - Awful Things feat. Lil Tracy (Official Video) (03:33) to begin playing 

but will not play 

### Expected Result

I expected the song to play!

### Debug Output

```
 Error when extracting data EID: d8fdf4c1-8088-4fa7-9f16-7ab2042f224f,
 [23:03:48] [ERROR] [LocalAudioTrackExecutor]: Error in playback of zOujzvtwZ6M
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Windows Server 2019
  os.version: 10.0
  java.vendor: Eclipse Adoptium
  java.version: 11.0.13
  java.runtime.version: 11.0.13+8
  java.vm.version: 11.0.13+8
Caused by: java.lang.RuntimeException: Error when extracting data EID: d8fdf4c1-8088-4fa7-9f16-7ab2042f224f, mainJson <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:71)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:46)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video info response: 410
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:155)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackArgsFromVideoInfoPage(DefaultYoutubeTrackDetailsLoader.java:227)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:98)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:60)
	... 8 common frames omitted
[23:04:37] [WARN] [ExceptionTools]: Error when extracting data EID: 93337784-a367-4a6d-9299-b429e9d31d32,
[23:04:37] [ERROR] [LocalAudioTrackExecutor]: Error in playback of zOujzvtwZ6M
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Windows Server 2019
  os.version: 10.0
  java.vendor: Eclipse Adoptium
  java.version: 11.0.13
  java.runtime.version: 11.0.13+8
  java.vm.version: 11.0.13+8
Caused by: java.lang.RuntimeException: Error when extracting data EID: 93337784-a367-4a6d-9299-b429e9d31d32, mainJson <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:71)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:46)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video info response: 410
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:155)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackArgsFromVideoInfoPage(DefaultYoutubeTrackDetailsLoader.java:227)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:98)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:60)
	... 8 common frames omitted

```

### Additional Info

I had to remove some characters from the stack trace because it was too long 

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-04-24 23:40
Duplicate of #1026

**Closed by MichailiK** 2022-04-24 23:40 UTC
