### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by sh1nycube** [jagrosh/MusicBot#1769] opened 2024-11-24 06:07 UTC
### Bug Description

when i try to play anything from youtube it does this

`[00:44:27] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/89dfc5b3/player_ias.vflset/en_US/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\me\AppData\Local\Temp\lavaplayer-yt-player-script8211637692447611812.js

[00:44:27] [ERROR] [AudioHandler]: Track 8dtzMPApA4M has failed to play com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`

### Steps to Reproduce

1. start the bot
2. join vc 
3. play any yt link

### Expected Result

playing music

### Debug Output

```
System Properties:
  java.version = 11.0.25
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.25+9
  java.specification.version = 11
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.3
  Owner = 835181141300215888
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 254
  Used Memory = 94

Discord Information:
  ID = 1310107383053422622
  Guilds = 1
  Users = 6
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment] 2024-11-24 18:38
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-11-24 18:38 UTC
