### ISSUE TITLE
Announce new song in chat 

### ISSUE THREAD

**Issue by ItsJakeo** [jagrosh/MusicBot#769] opened 2021-09-12 14:16 UTC
Have the ability to announce a new song in the chatbox when the song starts. 
Have the option in config file to turn on or off announce songs.

**Comment by DJMoffinz** [comment] 2021-09-13 04:23
That’s a good idea.

**Comment by very-lame-username** [comment] 2021-09-13 10:43
You could also just call nowplaying at the start of each song and delete the old one to keep it effectively pinned.

**Comment by StargazerVoyager** [comment] 2021-09-21 23:59
Yes please, I'm very much interested in this feature!

**Comment by jagrosh** [comment] 2021-09-27 18:39
Duplicate of #353

**Closed by jagrosh** 2021-09-27 18:39 UTC
Labels: enhancement
