### ISSUE TITLE
[Feature Request] Title Here

### ISSUE THREAD

**Issue by JesperKuipers** [jagrosh/MusicBot#1280] opened 2023-02-10 16:15 UTC
### Is your feature request related to a problem? Please describe.

It's kinda annoying having the console in taskbar.

### What is your ideal solution to the problem?

have a button to move it to "hidden icons" menu on the taskbar

### How would this feature be used?

1. click button
2. have console be hidden from taskbar and move it to

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2023-02-10 16:16
Duplicate of #546

**Closed by MichailiK** 2023-02-10 16:16 UTC
