### ISSUE TITLE
[Bug Report] I have a this proble with a bot

### ISSUE THREAD

**Issue by mihajlo1005** [jagrosh/MusicBot#1626] opened 2024-07-24 23:27 UTC
### Bug Description

[23:21:05] [ERROR] [AudioHandler]: Track nkbakcHNAs4 has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Sign in to confirm you’re not a bot
        at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

### Steps to Reproduce

i type to play music and link of the music and this error appears in hosting console

### Expected Result

To fix this bug

### Debug Output

i dont know

### Additional Info

i dont know

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

Version 0.4.2

**Comment by MichailiK** [comment] 2024-07-25 07:15
Duplicate of #1588

**Closed by MichailiK** 2024-07-25 07:15 UTC
