### ISSUE TITLE
[Bug Report] [WARN] [RateLimiter]: Encountered 429 on route /channels/

### ISSUE THREAD

**Issue by BigDGaming** [jagrosh/MusicBot#429] opened 2020-05-30 09:11 UTC
**Describe the bug**

**To Reproduce**
1. Attempt to play a song

**Expected behavior**
[19:10:18] [WARN] [RateLimiter]: Encountered 429 on route /channels/633269098725507082
Bot appears in voip channel, then discounts.

**Screenshots**
n/a

**Debug Info**
n/a

**Additional context**
n/a

**Comment by jagrosh** [comment] 2020-05-30 15:29
Duplicate of #417

**Closed by jagrosh** 2020-05-30 15:29 UTC
