### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by PatriotRBX** [jagrosh/MusicBot#1242] opened 2022-11-13 14:10 UTC
### Is your feature request related to a problem? Please describe.

How do you make the bot be able to be used with slash commands? 

### What is your ideal solution to the problem?

The bot to be able to use slash commads. 

### How would this feature be used?

1. /play or /skip 

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-11-13 14:23
Duplicate of #664

**Closed by MichailiK** 2022-11-13 14:23 UTC
