### ISSUE TITLE
[Bug Report] Title Here 

### ISSUE THREAD

**Issue by tiagocomti** [jagrosh/MusicBot#1151] opened 2022-04-07 13:49 UTC
### Bug Description

cant set my youtube playlist on my bot

### Steps to Reproduce

1. !play https://www.youtube.com/watch?v=n6sluyWFDDc&list=RDMM&index=6

### Expected Result

play our playlist https://www.youtube.com/watch?v=n6sluyWFDDc&list=RDMM&index=6

### Debug Output

[10:47:11] [WARN] [DefaultAudioPlayerManager]: Suspicious exception for loading item https://www.youtube.com/watch?v=n6sluyWFDDc&list=RDMM&index=6
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Could not find tracks from mix.
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMixProvider.load(YoutubeMixProvider.java:66)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:252)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:228)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:94)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:64)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:42)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:131)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: FreeBSD
  os.version: 11.2-RELEASE-p3
  java.vendor: OpenJDK BSD Porting Team
  java.version: 16.0.1
  java.runtime.version: 16.0.1+9-1
  java.vm.version: 16.0.1+9-1

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-04-07 14:07
Duplicate of #1147

**Closed by MichailiK** 2022-04-07 14:07 UTC
