### ISSUE TITLE
[Feature Request] deafen the bot

### ISSUE THREAD

**Issue by TheYeetster1** [jagrosh/MusicBot#1015] opened 2021-10-30 17:46 UTC
### Is your feature request related to a problem? Please describe.

The bot is not deafened, there is no reason for it to receive audio from a voice channel. I'm unsure if having the bot deafened would reduce bandwidth used, but it would increase the confidence of anyone who uses the bot.

### What is your ideal solution to the problem?

Have the bot either deafen, or server deafen itself and prevent tampering.

### How would this feature be used?

1.Run the bot
2.Play video
3.Bot joins deafened

### Additional Info

```
voiceChannel.join()
  .then(connection => {
      connection.voice.setSelfDeaf(true);
  });
```

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2021-10-30 17:58
Duplicate of #519

**Closed by MichailiK** 2021-10-30 17:58 UTC
