### ISSUE TITLE
[Feature Request] anyone can create there own playlist

### ISSUE THREAD

**Issue by RootAndroid58** [jagrosh/MusicBot#316] opened 2019-11-13 13:02 UTC
**Is your feature request related to a problem? Please describe.**
the command p.playlist <append|delete|make|setdefault> is only for owner but can u make this command available to everyone example server admin only command

**Comment by jagrosh** [comment] 2019-11-13 16:13
Duplicate of #24 and/or #311

**Closed by jagrosh** 2019-11-13 16:13 UTC
