### ISSUE TITLE
[Bug Report] Impossible to play

### ISSUE THREAD

**Issue by YouKyi** [jagrosh/MusicBot#430] opened 2020-05-30 13:51 UTC
Hello, i follow the guide and i have an error..

15:49:35] [ERROR] [LocalAudioTrackExecutor]: Error in playback of jH1RNk8954Q
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: null
	at java.base/java.net.URI$Parser.parse(URI.java:3129)
	at java.base/java.net.URI.<init>(URI.java:623)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	... 4 common frames omitted

**Comment by Catdontpat** [comment] 2020-05-30 15:13
For this, it’s not really an issue,

Are you currently running jdk 13? And not running any other version of java by chance?

**Comment by Catdontpat** [comment] 2020-05-30 15:14
If you aren’t, this is something you may wanna do

I would take the time to install jdk 13 and reconfigure your java paths and more to make it run that version

As it seems jre 8 is no longer supported and jdk 14 is still not fully supported and has a ton of issues when attempting to use it for steaming music.

**Comment by jagrosh** [comment] 2020-05-30 15:28
Duplicate of #417

**Closed by jagrosh** 2020-05-30 15:28 UTC
