### ISSUE TITLE
Yotube can't be played. Other sites work

### ISSUE THREAD

**Issue by Cristofor69** [jagrosh/MusicBot#1752] opened 2024-11-06 19:07 UTC
### Bug Description

When I try to play youtube it joins and exist immediately but other sites like soundcloud work.
I get the error

[20:53:40] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/dad5a960/player_ias.vflset/en_GB/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\User\AppData\Local\Temp\lavaplayer-yt-player-script1440105868000145281.js
[20:53:41] [ERROR] [AudioHandler]: Track 8hlDIoNJNBI has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at j
![Screenshot 2024-11-06 210540](https://github.com/user-attachments/assets/58db8a07-e2d3-4799-8578-0405ceec0acd)
ava.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

Any youtube link

### Expected Result

I expected to listen to youtube

### Debug Output

![Screenshot 2024-11-06 210540](https://github.com/user-attachments/assets/3e409d1a-5627-4db6-bd2d-b3f312559c23)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by DaanSelen** [comment] 2024-11-07 12:10
Will this be fixed? My bot has been unable to play youtube videos, and that is what I have it for... Or is there a way I can make it work again?

**Comment by MichailiK** [comment] 2024-11-07 12:53
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-11-07 12:53 UTC
