### ISSUE TITLE
[Feature Request] Edit message templates

### ISSUE THREAD

**Issue by IngwiePhoenix** [jagrosh/MusicBot#1202] opened 2022-08-23 22:34 UTC
### Is your feature request related to a problem? Please describe.

There is a running joke going around our discord server which lead me to a nice idea in terms of personalizing self-hosted instances: Editing the reply messages, or more specifially, the templates.

The idea is that the user may specify templateable strings that will be used to send replies. For instance, when `!stop` is used, a custom message is sent in return.

Would love to have that to not just keep our joke going in our lil' place, but it'd also be neat for further customization!

Thanks :)

### What is your ideal solution to the problem?

A command to configure the templates.

### How would this feature be used?

```
!config msg stop Thank you for listening, hear you soon!
```

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2022-08-26 13:22
Effectively a duplicate of #689 since custom messages would be possible by swapping out the localization.

**Closed by jagrosh** 2022-08-26 13:22 UTC
