### ISSUE TITLE
[Bug Report] Can't Play Music(Youtube URL)

### ISSUE THREAD

**Issue by Lapius7** [jagrosh/MusicBot#1633] opened 2024-07-31 20:50 UTC
### Bug Description

「{Prefix}play {YoutubeURL}」コマンドを使用し、音楽を再生しようとするとボットがVCに参加してから直ぐに抜けてしまいます。

### Steps to Reproduce

Playコマンドを使用する。

### Expected Result

音楽が再生される

### Debug Output

[05:41:34] [INFO] [JMusicBot]: Loaded config from C:\Users\20071\OneDrive\デスクトップ\Discord-MusicBot\.english\config.txt
[05:41:34] [INFO] [JDA]: Login Successful!
[05:41:35] [INFO] [WebSocketClient]: Connected to WebSocket
[05:41:35] [INFO] [JDA]: Finished Loading!
[05:42:07] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/20dfca59/player_ias.vflset/ja_JP/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\20071\AppData\Local\Temp\lavaplayer-yt-player-script1518192463622086614.js
[05:42:08] [ERROR] [LocalAudioTrackExecutor]: Error in playback of tFcusl55yIk
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:268)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:140)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:108)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101)
	... 4 common frames omitted
[05:42:08] [ERROR] [AudioHandler]: Track tFcusl55yIk has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:268)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:140)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:108)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101)
	... 4 common frames omitted

### Additional Info

日本語版ならちゃんと動きますが、英語版の方が少し多機能なので修正してほしいです。
https://github.com/Cosgy-Dev/JMusicBot-JP

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.2

**Comment by Akint2x** [comment] 2024-07-31 20:51
Wait for new jar version.

**Comment by Lapius7** [comment] 2024-07-31 21:04
> 新しいjarバージョンを待ちます。

Does that mean I should wait for Version 0.4.3?

**Comment by Akint2x** [comment] 2024-07-31 21:06
Yes

**Comment by Lapius7** [comment] 2024-07-31 21:07
Are you experiencing the same bug?

**Comment by Akint2x** [comment] 2024-07-31 21:09
> Does everyone have the bug?

Yes.

**Comment by Lapius7** [comment] 2024-07-31 21:10
> > Does everyone have the bug?
> 
> Yes.

I'm relieved to know I'm not the only one with this bug.

**Comment by Lapius7** [comment] 2024-07-31 21:10
thx

**Comment by Crytkee** [comment] 2024-07-31 22:07
time to wait for new jar :pray: 😭😭😭

**Comment by Oxbow117** [comment] 2024-08-01 03:31
i love your pfp

**Comment by Lapius7** [comment] 2024-08-01 05:50
> Wait for new jar version.

Do you have a rough idea of ​​how many days later you will be able to release the revised version?

**Comment by Akint2x** [comment] 2024-08-01 05:57
If you want you can use from my git repo or wait for official version

**Comment by Lapius7** [comment] 2024-08-01 06:11
I don't know much about git, so I don't know much about it.

**Comment by Akint2x** [comment] 2024-08-01 06:16
> I don't know much about git, so I don't know much about it.

https://github.com/Akint2x/MusicBot/releases

PS: sorry for link here - my private repo  but i love MusicBot

**Comment by Lapius7** [comment] 2024-08-01 06:18
Is that the bug-fixed version?

postscript
I'm Japanese, so my English may be wrong.

**Comment by Lapius7** [comment] 2024-08-01 07:52
https://github.com/Akint2x/MusicBot/releases/tag/JMusicBot-0.4.2f
I tried introducing it, but it still crashes immediately.

**Comment by Akint2x** [comment] 2024-08-01 09:47
sorry my mistake now its works

**Comment by IrGaaT** [comment] 2024-08-01 10:40
Thank you Akint2x works perfectly.

**Comment by Lapius7** [comment] 2024-08-01 11:40
ty
i try

**Comment by Lapius7** [comment] 2024-08-01 11:48
It worked fine! thank you!!
However, as shown in the image below, is there anything I can do to get rid of the DM that comes every time I start up?
![スクリーンショット 2024-08-01 204808](https://github.com/user-attachments/assets/dede5557-a31a-4814-8571-88170e2e9f9a)

**Comment by Lapius7** [comment] 2024-08-01 11:51
It worked fine! thank you!!
However, as shown in the image below, is there anything I can do to get rid of the DM that comes every time I start up?
![スクリーンショット 2024-08-01 204808](https://github.com/user-attachments/assets/dede5557-a31a-4814-8571-88170e2e9f9a)

**Comment by Sirdo2k22** [comment] 2024-08-01 12:28
You'll get a message when Jagrosh will  public 0.4.x official. Now just ignor it. Its unofficial

**Comment by Lapius7** [comment] 2024-08-01 12:40
ok
very ty support

**Comment by ofoxus** [comment] 2024-08-01 12:40
Thank you Akint2x! It works great

**Comment by jagrosh** [comment] 2024-08-01 12:59
Duplicate of #1630

**Closed by jagrosh** 2024-08-01 12:59 UTC
