### ISSUE TITLE
[Bug Report] Please sign in to play.

### ISSUE THREAD

**Issue by Fetakungen** [jagrosh/MusicBot#1729] opened 2024-10-19 11:02 UTC
### Bug Description

Youtube does not play.

### Steps to Reproduce

Start bot, play youtube video.

### Expected Result

Play video.

### Debug Output

[09:23:37] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id succeeded, new one is CgtmUThYUDlBQldtVSiZ9c24BjIiCgJTRRIcEhgSFgsMDg8QERITFBUWFxgZGhscHR4fICEgZjoMCAEgiYH-4ZHT3oln, next update will be after 600 seconds.
[09:23:37] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of SY-h-sGn2XM
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[09:23:37] [ERROR] [AudioHandler]: Track SY-h-sGn2XM has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment] 2024-10-19 11:41
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-19 11:41 UTC
