### ISSUE TITLE
[Bug Report] Bot won't play music

### ISSUE THREAD

**Issue by mrfroncu** [jagrosh/MusicBot#550] opened 2020-11-01 22:23 UTC
**Describe the bug**
Bot won't play music
**To Reproduce**

```
[23:15:29] [INFO] [JDA]: Finished Loading!
[23:15:57] [ERROR] [LocalAudioTrackExecutor]: Error in playback of aWmkuH1k7uA
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:136)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
        ... 4 common frames omitted

```

**Debug Info**
```
System Properties:
  java.version = 1.8.0_201
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_201-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.1
  Owner = 24880473278788XXXX
  Prefix = $
  AltPrefix = `
  MaxSeconds = 0
  NPImages = true
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_212
  JDA-Utilities Version = 3.0.4
  Lavaplayer Version = 1.3.59

Runtime Information:
  Total Memory = 31
  Used Memory = 24

Discord Information:
  ID = 41631710586103XXXX
  Guilds = 1
  Users = 2
```

**Comment by jagrosh** [comment] 2020-11-01 22:25
Duplicate of #531

**Closed by jagrosh** 2020-11-01 22:25 UTC
