### ISSUE TITLE
support spotify

### ISSUE THREAD

**Issue by amirwopi** [jagrosh/MusicBot#1201] opened 2022-08-21 12:34 UTC
### Is your feature request related to a problem? Please describe.

support spotify

### What is your ideal solution to the problem?

support spotify

### How would this feature be used?

support spotify

### Additional Info

support spotify

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-08-21 12:45
Duplicate of #66

**Closed by MichailiK** 2022-08-21 12:45 UTC
