### ISSUE TITLE
[Bug Report] Player jumping around when moving channels

### ISSUE THREAD

**Issue by Soitora** [jagrosh/MusicBot#431] opened 2020-05-30 20:10 UTC
**Describe the bug**
After todays update when moving the bot between channels it disconnects and reconnects directly after moving it.

**To Reproduce**
1. Have music playing
2. Move bot
3. See bot jumping in and out after move

**Expected behavior**
It should move, simply, as before.

**Screenshots**
https://gfycat.com/DiligentGlassIberianchiffchaff

**Debug Info**
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/4706361/debug_information.txt)

**Additional context**
Only occured after todays update, restarting does nothing.

**Comment by jagrosh** [comment] 2021-02-09 15:04
Closing as there have been several changes to both the dependencies of the bot and Discord's voice servers since this was opened. If this can still be reproduced, feel free to reopen this issue or make a new one with updated info.

**Closed by jagrosh** 2021-02-09 15:04 UTC
