### ISSUE TITLE
bot connects but doesn't play music on 0.4.0 , works fine on 0.3.9

### ISSUE THREAD

**Issue by Moesam961** [jagrosh/MusicBot#1533] opened 2024-03-31 23:00 UTC
### Bug Description

bot loads as usual and can be summoned to discord channel but doesn't play music, it connects and finds whatever music i queue but no sound comes out of it

### Steps to Reproduce

open bot
wait for it to load
loads successfully
use music command

### Expected Result

the bot plays music

### Debug Output

version 0.4.0 

### Additional Info

01:43:10] [INFO] [JMusicBot]: Loaded config from C:\Users\H4L\MusicBot\config.txt
[01:43:10] [INFO] [JDA]: Login Successful!
[01:43:11] [INFO] [WebSocketClient]: Connected to WebSocket
[01:43:11] [INFO] [JDA]: Finished Loading!
[01:43:41] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id (current is null).
[01:43:42] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id succeeded, new one is CgttVlBWSlNRNmMtYyidzqewBjIKCgJMQhIEGgAgTjoKII_gmcHS4_mEZg%3D%3D, next update will be after 600 seconds.
[01:53:54] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id (current is CgttVlBWSlNRNmMtYyidzqewBjIKCgJMQhIEGgAgTjoKII_gmcHS4_mEZg%3D%3D).
[01:53:54] [INFO] [YoutubeAccessTokenTracker]: Updating YouTube visitor id succeeded, new one is CgtLOTVBY0dubHUxQSiC06ewBjIKCgJMQhIEGgAgTToKIIiOxaSmsPqEZg%3D%3D, next update will be after 600 seconds.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-03-31 23:04
Duplicate of #1529

**Closed by jagrosh** 2024-03-31 23:04 UTC
