### ISSUE TITLE
Major error in bot console

### ISSUE THREAD

**Issue by joeyk710** [jagrosh/MusicBot#659] opened 2021-04-01 22:13 UTC
When the bot is running, sometimes it produces this major error in the console and I have no idea how to fix it no matter how many times the bot is restarted. Nothing is wrong with the bot. I am wondering why this comes up in the console.

```
[12:40:00] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of q_9SsX7HJhE
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Track information is unavailable.
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackBaseInfoFromEmbedPage(DefaultYoutubeTrackDetailsLoader.java:200)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:88)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:45)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.67
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 11.0.10
  java.runtime.version: 11.0.10+8-LTS-162
  java.vm.version: 11.0.10+8-LTS-162
Caused by: java.lang.IllegalStateException: Expected player config is not present in embed page.
	... 11 common frames omitted
```

**Comment by jagrosh** [comment] 2021-04-01 22:18
Duplicate of #658, also please use the template.

**Closed by jagrosh** 2021-04-01 22:18 UTC
