### ISSUE TITLE
[Feature Request] Allow non-owners to append songs to a playlist

### ISSUE THREAD

**Issue by Johnnyhoboy** [jagrosh/MusicBot#745] opened 2021-08-29 23:16 UTC
**Is your feature request related to a problem? Please describe.**
Not related to a current problem, but I've dived into the source code and realized that there is no support for compiling my own jar.

**Describe the solution you'd like**
Expand playlist permissions so that non-owners can use the "playlist append <playlistname> <item> | [item] | [item]" command. I wish for other people in my server to add in their own youtube links to an existing playlist, so we can have a community curated playlist.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1.  Allows non-server-owners to use the playlist append command to add their own links to an existing playlist similar to the owner

**Additional context**
Perhaps allow similar functionality to the setdj command but "setowner" to a particular server role

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

**Comment by jagrosh** [comment] 2021-08-29 23:17
Duplicate of #24

**Closed by jagrosh** 2021-08-29 23:17 UTC
