### ISSUE TITLE
Discord Bot does not play music

### ISSUE THREAD

**Issue by MakeItGame** [jagrosh/MusicBot#662] opened 2021-04-02 12:17 UTC
**Describe the bug**
When i try to play a normal youtube link, the bot joins the channel but does not begin playing and just leaves a huge text in the console

**To Reproduce**
1. Join a channel on discord
2. type the play command with an yt link
3. watch the console

**Expected behavior**
The bot does not play music and leaves a gigantic text in the console

**Screenshots**
https://user-images.githubusercontent.com/55139316/113414714-2ee02980-93ad-11eb-906e-d7ed7528f4d0.mp4

**Debug Info**
System Properties:
  java.version = 1.8.0_252
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_252-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.3
  Owner = 376648962570059796
  Prefix = m
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_227
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.67

Runtime Information:
  Total Memory = 27
  Used Memory = 15

Discord Information:
  ID = 826378389832728587
  Guilds = 1
  Users = 2

**Additional context**
Replace this text with any other context about the problem.

**Comment by MichailiK** [comment] 2021-04-02 12:36
Duplicate of #658

**Closed** 2021-04-02 14:49 UTC
