### ISSUE TITLE
[Feature Request] Limit queue per-user.

### ISSUE THREAD

**Issue by tlworks** [jagrosh/MusicBot#668] opened 2021-04-07 23:44 UTC
**Is your feature request related to a problem? Please describe.**
Related to the example in the additional context, prevent users from adding too many songs to the queue.

**Describe the solution you'd like**
Able to set queue limit per-user to prevent users from adding too many songs to the queue.

**Describe the basic flow/steps of using this feature**
Able to set queue limit per-user by either role permission or config option.

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/19647337/113947637-60248380-980b-11eb-9ef9-c231de5a46b0.png)

**Comment by jagrosh** [comment] 2021-04-08 00:26
This is effectively a duplicate of #485, just with slightly different context.

**Closed by jagrosh** 2021-04-08 00:26 UTC
