### ISSUE TITLE
[Bug Report] Title Here

### ISSUE THREAD

**Issue by ancar0** [jagrosh/MusicBot#478] opened 2020-08-08 12:06 UTC
**Describe the bug**
The bot doesn't play any song or playlist. It disconnects.

**To Reproduce**
When doing  [prefix]Play [Link]  the bot doesn't play it. It spams errors(in debug) and disconnects.

**Expected behavior**
Play the music/song.

![unknown (3)](https://user-images.githubusercontent.com/49865848/89710051-c0f77580-d977-11ea-94bf-8854a22e76b2.png)

**Debug Info**
[12:58:33] [INFO] [Startup]: Loaded config from Z:\Public_Bots\Music IT\config.txt
[12:58:34] [INFO] [JDA]: Login Successful!
[12:58:34] [INFO] [WebSocketClient]: Connected to WebSocket
[12:58:35] [INFO] [JDA]: Finished Loading!
[12:58:41] [ERROR] [LocalAudioTrackExecutor]: Error in playback of Tc-XxqEyolU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 429
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:28)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:75)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video page response: 429
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:39)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:26)
	... 7 common frames omitted
[12:58:41] [WARN] [RateLimiter]: Encountered 429 on route /channels/714796928776536074

**Comment by Sanduhr32** [comment] 2020-08-08 12:19
429, youtube blocked you because your behavior looked like intentional spam. You have to wait it out or change your IP address.

**Comment by jagrosh** [comment] 2020-08-08 15:06
Duplicate of #305

**Closed by jagrosh** 2020-08-08 15:06 UTC
