### ISSUE TITLE
[Feature Request] locales

### ISSUE THREAD

**Issue by 6102yk** [jagrosh/MusicBot#837] opened 2021-09-17 10:10 UTC
**Is your feature request related to a problem? Please describe.**
A feature that we can change languages through commands

**Describe the solution you'd like**
Replace this text with a clear and concise description of what you want to happen.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Change bot different languages

**Additional context**

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

**Comment by MichailiK** [comment] 2021-09-17 10:11
Duplicate of #689.

**Closed by MichailiK** 2021-09-17 10:11 UTC
