### ISSUE TITLE
[Bug Report] Bot not responding to prefix

### ISSUE THREAD

**Issue by Gartral** [jagrosh/MusicBot#1268] opened 2023-01-15 07:41 UTC
### Bug Description

the bot doesn't respond to any prefix set except "@mention"

### Steps to Reproduce

1. install bot
2. test with @mention and bot works
3. change prefix to "mb! "
4. restart bot
5. bot no longer responds to any commands

### Expected Result

Bot responds correctly.

### Debug Output

Ubuntu 22.04, openjdk 17.0.5, JMusicBot 0.3.8

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2023-01-15 08:14
Duplicate of #1215

**Closed by jagrosh** 2023-01-15 08:14 UTC
