### ISSUE TITLE
[Bug Report] Please sign in error when playin music from youtube

### ISSUE THREAD

**Issue by ishyy1** [jagrosh/MusicBot#1726] opened 2024-10-17 21:23 UTC
### Bug Description

whenever I want to play music I get an error saying Track MpUViv00u5Y has failed to play com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in.
I saw different people mentioning simmilar errors but those said "Something broke when playing the track." or "Sign in to confirm you’re not a bot" but for me its just "Please sign in".

### Steps to Reproduce

1. Play any song

### Expected Result

Music starts playing

### Debug Output

```
System Properties:
  java.version = 11.0.24
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.24+8
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.4.3
  Owner = 459762912685457428
  Prefix = @mention
  AltPrefix = ?
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 502
  Used Memory = 137

Discord Information:
  ID = 1296568601272254515
  Guilds = 1
  Users = 3
```

### Additional Info

console output:
[23:16:42] [ERROR] [AudioHandler]: Track MpUViv00u5Y has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by Ghosttne** [comment] 2024-10-17 21:26
I am also adding that I'm having this issue. I've yet to figure out why.

**Comment by TheTrueShadow** [comment] 2024-10-17 21:56
This is known as seen here https://github.com/jagrosh/MusicBot/issues/1588#issue-2340450311
we will have to wait for an update for this to be fixed

**Comment by MichailiK** [comment] 2024-10-17 22:17
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-17 22:17 UTC
