### ISSUE TITLE
[Bug Report] Failure to search and auto restart

### ISSUE THREAD

**Issue by onlyyouX2** [jagrosh/MusicBot#521] opened 2020-10-21 10:35 UTC
Hello, I have a problem, but I did not know the solution to this problem.
And sometimes he log out and log in in the room , It appears when searching 💡 No results found for
When repeating is running.
I checked all the things and the connection, the problem was not solved What is the solution?

Thank you .

Error message :
[22:37:35] [ERROR] [Requester]: There was an exception while executing a REST request
java.net.UnknownHostException: discordapp.com
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
	at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at okhttp3.Dns.lambda$static$0(Dns.java:39)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:191)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116)
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:350)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by onlyyouX2** [comment] 2020-10-21 11:24
[04:22:11] [WARN] [YoutubeSearchProvider]: Failed to match ytInitialData JSON object
[04:22:17] [WARN] [YoutubeSearchProvider]: Failed to match ytInitialData JSON object
[04:22:56] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$156/2092114999@509dfd86
[04:22:56] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: successfully loaded.
[04:22:56] [INFO] [NativeLibraryLoader]: Native library connector: loading with filter null
[04:22:56] [INFO] [NativeLibraryLoader]: Native library connector: successfully loaded.

**Comment by onlyyouX2** [comment] 2020-10-21 11:25
**💡 No results found for** 
[04:22:11] [WARN] [YoutubeSearchProvider]: Failed to match ytInitialData JSON object
[04:22:17] [WARN] [YoutubeSearchProvider]: Failed to match ytInitialData JSON object
[04:22:56] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$156/2092114999@509dfd86
[04:22:56] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: successfully loaded.
[04:22:56] [INFO] [NativeLibraryLoader]: Native library connector: loading with filter null
[04:22:56] [INFO] [NativeLibraryLoader]: Native library connector: successfully loaded.

**Comment by onlyyouX2** [comment] 2020-10-21 12:11
Mr. John Grosh
Hope you can help me
Thank you .

**Comment by teorailin** [comment] 2020-10-22 16:44
Same

**Comment by Baron010** [comment] 2020-10-23 12:15
yeah same

**Comment by lordbinchicken** [comment] 2020-10-23 19:09
it's a Lavaplayer issue, this is being fixed in the next update of MusicBot, this issue is a dupe of #520, #517, #515

**Comment by jagrosh** [comment] 2020-10-23 19:33
Duplicate of #520

**Closed by jagrosh** 2020-10-23 19:33 UTC
