### ISSUE TITLE
[Bug Report] YouTube gets broken after 2nd song.

### ISSUE THREAD

**Issue by 3Trex** [jagrosh/MusicBot#1722] opened 2024-10-16 01:16 UTC
### Bug Description

After 2 songs the YouTube request gets broken. (Can't paly anything on YouTube until restart)

### Steps to Reproduce

1. Login Voice chat
2. Do !play command to play youtube
3. After 2nd song YouTUbe gets broken

### Expected Result

Play youtube music.

### Debug Output

[02:12:20] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of U4ZPHtzmvCE
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[02:12:20] [ERROR] [AudioHandler]: Track U4ZPHtzmvCE has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Additional Info

Currently using Jmusicbot 0.4.3.1 (Tried with 0.4.3) too, but not works.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3.1

**Comment by superboy200** [comment] 2024-10-16 13:23
where you got version 0.4.3.1?

**Comment by Tomberryy** [comment] 2024-10-16 13:30
Your IP has been identified as a bot by youtube. I had the same issue when using a VPS that was rang banned so I hosted it on my PI at home but yesterday it also got flagged.

Gotta wait for https://github.com/jagrosh/MusicBot/pull/1670 I guess...

**Comment by 3Trex** [comment] 2024-10-16 13:52
> where you got version 0.4.3.1?

On their Discord.

**Comment by 3Trex** [comment] 2024-10-16 13:53
> Your IP has been identified as a bot by youtube. I had the same issue when using a VPS that was rang banned so I hosted it on my PI at home but yesterday it also got flagged.
> 
> Gotta wait for #1670 I guess...

Even if I use a VPN would't fix it? I have a paid VPN.

**Comment by Tomberryy** [comment] 2024-10-16 14:02
> > Your IP has been identified as a bot by youtube. I had the same issue when using a VPS that was rang banned so I hosted it on my PI at home but yesterday it also got flagged.
> > Gotta wait for #1670 I guess...
> 
> Even if I use a VPN would't fix it? I have a paid VPN.

Maybe, until youtube deem your vpn range as "must be logged on" by youtube api, if it's not already the case

**Comment by 3Trex** [comment] 2024-10-16 14:08
Well I talked to A locked NUTS (developer)
![Discord_IJZx7GSEDP](https://github.com/user-attachments/assets/12cdf129-da52-4bcc-8e89-94ac79bb3931)
![Discord_OC2uLZaa0q](https://github.com/user-attachments/assets/b57fbb73-88cb-45ea-8699-1a03f2923ad9)

This is what he/she said. 


Currently using :  [JMusicBot-0.4.3-yt-oauth2-348fc3c.jar]
Tried with VPN also, some videos not plays at all. :(

**Comment by LennBoedd** [comment] 2024-10-16 15:12
> Well I talked to A locked NUTS (developer) ![Discord_IJZx7GSEDP](https://private-user-images.githubusercontent.com/43248490/377088893-12cdf129-da52-4bcc-8e89-94ac79bb3931.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTE3NzUsIm5iZiI6MTcyOTA5MTQ3NSwicGF0aCI6Ii80MzI0ODQ5MC8zNzcwODg4OTMtMTJjZGYxMjktZGE1Mi00YmNjLThlODktOTRhYzc5YmIzOTMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE1MTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNDgwY2MwODllNjkxMzQzMzg4MWJjY2I1M2U0MjA2MGU2ZmQ4YjA1OGI3ZTVhNGNhNWVmODVkZGQ5MTNhNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UrssNwQ1KWM982dNVmOm_K7QBUUidioudSbU_ocoOSE) ![Discord_OC2uLZaa0q](https://private-user-images.githubusercontent.com/43248490/377088899-b57fbb73-88cb-45ea-8699-1a03f2923ad9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTE3NzUsIm5iZiI6MTcyOTA5MTQ3NSwicGF0aCI6Ii80MzI0ODQ5MC8zNzcwODg4OTktYjU3ZmJiNzMtODhjYi00NWVhLTg2OTktMWEwM2YyOTIzYWQ5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE1MTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MWFkODgxNGUxZjYzODJmOTlkMzg2NWVlYjk5NzcxNjYzZWM2MzM0ZTRjOTU0ZTdiYWM5NGQ4MGY4OTdmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WLsHL-Q8WMk2zNsCU5PFKf0tPmfjdoMmOp3LIKmZhrg)
> 
> This is what he/she said.
> 
> Currently using : [JMusicBot-0.4.3-yt-oauth2-348fc3c.jar] Tried with VPN also, some videos not plays at all. :(

Did they give an eta for 4.4?

**Comment by Tomberryy** [comment] 2024-10-16 15:55
> Well I talked to A locked NUTS (developer) ![Discord_IJZx7GSEDP](https://private-user-images.githubusercontent.com/43248490/377088893-12cdf129-da52-4bcc-8e89-94ac79bb3931.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODgxODcsIm5iZiI6MTcyOTA4Nzg4NywicGF0aCI6Ii80MzI0ODQ5MC8zNzcwODg4OTMtMTJjZGYxMjktZGE1Mi00YmNjLThlODktOTRhYzc5YmIzOTMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE0MTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZmE3NDRiOWM4NGM1N2MyZmZlMzgxODU2NjNlMTZjYWJmYTVhY2ZhMzFhOGRiOTcwZTEwMDgwZDQxYTIxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wDsbpa9-hhc7neuxvpWo_SS4nMND2Wev1159MPbhSRM) ![Discord_OC2uLZaa0q](https://private-user-images.githubusercontent.com/43248490/377088899-b57fbb73-88cb-45ea-8699-1a03f2923ad9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODgxODcsIm5iZiI6MTcyOTA4Nzg4NywicGF0aCI6Ii80MzI0ODQ5MC8zNzcwODg4OTktYjU3ZmJiNzMtODhjYi00NWVhLTg2OTktMWEwM2YyOTIzYWQ5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE0MTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZjQ4NmMyYzY3MzdlYmJmZjVjMjI5Yjc3NWNlNjMwYTBkN2M3ODU4MWU2MDAzNmUwY2M1MGFkMjhmYjQ2YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rRnQmlDPVHtHxF27kBAf9-rXTHwgbrtoBT_oXhzH6J0)
> 
> This is what he/she said.
> 
> Currently using : [JMusicBot-0.4.3-yt-oauth2-348fc3c.jar] Tried with VPN also, some videos not plays at all. :(

the yt-oauth worked like a charm for me, thanks for the tip

**Comment by Healzangels** [comment] 2024-10-16 16:24
Apologies for a basic question. Was hoping to test the OAuth YT option - not sure however where to acquire the build which includes it. Running on Docker for what it's worth. Cheers!

**Comment by MichailiK** [comment] 2024-10-16 20:21
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-16 20:21 UTC

**Comment by 3Trex** [comment] 2024-10-16 20:22
Thank you for the comment, after I "logged on with a fake google" seems working just fine =)

**Comment by Tomberryy** [comment] 2024-10-17 12:51
> Apologies for a basic question. Was hoping to test the OAuth YT option - not sure however where to acquire the build which includes it. Running on Docker for what it's worth. Cheers!

Hey, I found the experimental build on the [Jagrosh Discord](https://discord.gg/0p9LSGoRLu6Pet0k)

In the Bot Discussion > Support
Look for the first pinned message by Michaili and follow the steps to set up a google account to your bot.

This is experimental and not the main build so use it at your own discretion.

**Comment by 3Trex** [comment] 2024-10-17 13:07
> > Apologies for a basic question. Was hoping to test the OAuth YT option - not sure however where to acquire the build which includes it. Running on Docker for what it's worth. Cheers!
> 
> Hey, I found the experimental build on the [Jagrosh Discord](https://discord.gg/0p9LSGoRLu6Pet0k)
> 
> In the Bot Discussion > Support Look for the first pinned message by Michaili and follow the steps to set up a google account to your bot.
> 
> This is experimental and not the main build so use it at your own discretion.

Hi thanks the message yeah I use that experimental build, with a Google API. (Made a fake Google Account) and since then everything seems to work, some songs like rap or else which filtered adult content or else, it cannot be player but other then that 99.9% songs are playable rn

So I reccomend to make a fake Google Account and use the API with the bot.
