### ISSUE TITLE
[Bug Report] 18+ videos with log in requiring 

### ISSUE THREAD

**Issue by lynrayy** [jagrosh/MusicBot#1240] opened 2022-11-10 13:24 UTC
### Bug Description

Bot can't play videos that requiring authorization on youtube (example https://www.youtube.com/watch?v=Q3IzUyFrJU4)
I think it will be good if config has optional YT Api Key parameter 

![image](https://user-images.githubusercontent.com/59417884/201102702-dd64b3a8-f87c-4d97-bbd4-9facadedea8b.png)

### Steps to Reproduce

1. !play https://www.youtube.com/watch?v=Q3IzUyFrJU4
2. bot connected and disconnected back
3. got error in console (additional info)

### Expected Result

w

### Debug Output

System Properties:
  java.version = 17.0.3.1
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 17.0.3.1+2-LTS-6
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 11

JMusicBot Information:
  Version = 0.3.8
  Owner = 646343450534346773
  Prefix = >
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.0_352
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 220
  Used Memory = 57

Discord Information:
  ID = 1029089106329882634
  Guilds = 1
  Users = 2

### Additional Info

  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 17.0.3.1
  java.runtime.version: 17.0.3.1+2-LTS-6
  java.vm.version: 17.0.3.1+2-LTS-6
Caused by: java.lang.RuntimeException: Error when extracting data EID: 8869925f-178a-47d0-931d-860972069f93, mainJson <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:71)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:46)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video info response: 410
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:155)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackArgsFromVideoInfoPage(DefaultYoutubeTrackDetailsLoader.java:227)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:98)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:60)
	... 8 common frames omitted

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-11-10 13:25
Duplicate of #1026

**Closed by MichailiK** 2022-11-10 13:25 UTC
