### ISSUE TITLE
[Bug Report] Play song automatic close

### ISSUE THREAD

**Issue by metixdsc** [jagrosh/MusicBot#1738] opened 2024-10-25 15:11 UTC
### Bug Description

[17:08:02] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/fb725ac8/player_ias.vflset/fr_FR/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\Antoine\AppData\Local\Temp\lavaplayer-yt-player-script9784303936185792342.js
[17:08:03] [ERROR] [AudioHandler]: Track on9TXY8kYyk has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

idk

### Expected Result

i play songI place the order, he enters the living room and leaves

### Debug Output

```
System Properties:
  java.version = 11.0.25
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.25+9
  java.specification.version = 11
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.3
  Owner = 1256517107160449085
  Prefix = !
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 152
  Used Memory = 110

Discord Information:
  ID = 1298804031829053521
  Guilds = 1
  Users = 2
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.43

**Comment by MichailiK** [comment] 2024-10-25 16:59
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-25 16:59 UTC
