### ISSUE TITLE
MusicBot is not playing music after commanding it and immedeatly leaved

### ISSUE THREAD

**Issue by BTOBIAS125** [jagrosh/MusicBot#1753] opened 2024-11-07 18:19 UTC
### Bug Description

[19:13:38] [ERROR] [AudioHandler]: Track At8v_Yc044Y has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

1.start musicbot 4.3
2.command playing song

### Expected Result

playing music

### Debug Output

```
System Properties:
  java.version = 17.0.11
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 17.0.11+9
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 11

JMusicBot Information:
  Version = 0.4.3
  Owner = 934924269996085268
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = true
  UseEval = true
  UpdateAlerts = false

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 78
  Used Memory = 44

Discord Information:
  ID = 1243661125078351974
  Guilds = 1
  Users = 2
```

### Additional Info

I am not very skilled for this kind of things so can anybody help me what to do?
I am on windows 11 if that helps.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

4.3

**Comment by BTOBIAS125** [comment] 2024-11-07 18:22
I tryed doing and searched all other issues that are like i described . If somebody can help me with that i would be very thankful!

**Comment by MichailiK** [comment] 2024-11-07 20:13
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-11-07 20:13 UTC
