### ISSUE TITLE
[Feature Request] Fair-Queue Toggle/Option

### ISSUE THREAD

**Issue by ZealTaku** [jagrosh/MusicBot#922] opened 2021-09-26 02:22 UTC
### Is your feature request related to a problem? Please describe.

Fair-Queue system is useful, however not being able to toggle on or off as an admin via command or in the config files is quite frustrating when trying to host certain music events which fair-queue can get in the way of. Don't get me wrong, the fair queue feature is quite useful, just not in all circumstances, especially for event holders.

### What is your ideal solution to the problem?

Perhaps adding a command or toggle to enable and or disable fair-queue for users that wish to use/not use the feature. Perhaps this could be in the config files or within the bot itself.

### How would this feature be used?

Typing in a command or changing a true/false statement in the config files to allow you to decide whether or not fair queue should be enabled or not. Perhaps this could be in the config files as a true/false statement or as a command within the server. 

### Additional Info

Tleichte also made a post regarding this feature, the link is here: https://github.com/jagrosh/MusicBot/issues/581. I just hope my post will at least bring more attention to the fair queue feature and allow for more options to be available in regards to its usage.

### Checklist

- [x] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2021-09-27 18:40
Duplicate of #581

**Closed by jagrosh** 2021-09-27 18:40 UTC
