### ISSUE TITLE
[Feature Request] Ability to ban specific users from using the bot

### ISSUE THREAD

**Issue by MCterra10** [jagrosh/MusicBot#1069] opened 2021-12-07 12:53 UTC
### Is your feature request related to a problem? Please describe.

Abusive users who continuously add long songs to the playlist, and keep re-adding when removed, but aren't breaking server rules to warrant a proper mute.

### What is your ideal solution to the problem?

Ability for admins to use a command to block a user from using the bot

### How would this feature be used?

1. Run ?ban user#1234
2. User can no longer use bot commands

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2021-12-07 13:17
Duplicate of #28

**Closed by MichailiK** 2021-12-07 13:17 UTC
