### ISSUE TITLE
[Feature Request] / Comands

### ISSUE THREAD

**Issue by P4Katyusha** [jagrosh/MusicBot#1410] opened 2023-07-21 15:05 UTC
### Is your feature request related to a problem? Please describe.

Nope

### What is your ideal solution to the problem?

To be able to have / comands on the bot or if not be able to put in your own / comands

### How would this feature be used?

1. Start the bot
2. insted of useing the prefox you would use / comands

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2023-07-21 15:23
Duplicate of #664

**Closed by MichailiK** 2023-07-21 15:23 UTC
