### ISSUE TITLE
[Feature Request] Seek

### ISSUE THREAD

**Issue by fufihiuse** [jagrosh/MusicBot#1217] opened 2022-09-10 20:01 UTC
### Is your feature request related to a problem? Please describe.

A lot of times, videos (especially VODs) will have long intros it's worth skipping 

### What is your ideal solution to the problem?

Adding a seek command, that allows you to skip to a specific time in the video, i.e. seek 1:23:00

### How would this feature be used?

1. To seek to a specific time in a playing video

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-09-19 07:53
Duplicate of #469

**Closed by MichailiK** 2022-09-19 07:53 UTC
