### ISSUE TITLE
not playing music from youtube

### ISSUE THREAD

**Issue by pbanj** [jagrosh/MusicBot#428] opened 2020-05-29 23:22 UTC
`olExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
        at java.base/java.net.URI$Parser.parse(URI.java:3104)
        at java.base/java.net.URI.<init>(URI.java:600)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
        ... 4 common frames omitted
`

that's the output in the console. bot joins and then exits after a few seconds.

**Comment by jagrosh** [comment] 2020-05-29 23:37
Duplicate of #417

**Closed by jagrosh** 2020-05-29 23:37 UTC
