### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by pineapplee85** [jagrosh/MusicBot#549] opened 2020-11-01 20:06 UTC
Hi there,

When I ask the bot to play something it enters the voice chat briefly and then leaves. 

It did manage to play one song previously but does not work anymore. I even tried restarting it.
I have attached a picture of the console for help.

[https://i.ibb.co/fCK7ZyW/bug.png](url)

**Comment by MichailiK** [comment] 2020-11-01 20:45
Duplicate of #531

**Closed** 2020-11-01 21:45 UTC
