### ISSUE TITLE
[Bug Report] LavaPlayer: Something broke when playing the track.

### ISSUE THREAD

**Issue by kubo6472** [jagrosh/MusicBot#542] opened 2020-10-30 19:54 UTC
**Describe the bug**
Lavaplayer error

**To Reproduce**
Play a track

**Expected behavior**
Play the track

**Debug Info**
LOGS: https://hastebin.com/apeneyafaw.less

**Comment by mooseh** [comment] 2020-10-30 21:13
Same issue for me too

**Comment by jagrosh** [comment] 2020-10-30 21:15
Duplicate of #531

**Closed by jagrosh** 2020-10-30 21:15 UTC
