### ISSUE TITLE
[Bug Report] Can't Play Music 

### ISSUE THREAD

**Issue by DeNNYHZ** [jagrosh/MusicBot#1732] opened 2024-10-21 07:53 UTC
### Bug Description

Hello there, I'm currently facing this problem. Where I wanted to play a music and the bot didn't start the music but instead it's error appeared on the jar file

### Steps to Reproduce

1. Start the bot
2. Join the voice channel
3. <prefix>play <music title>

### Expected Result

The song supposed to play but it's return error 

### Debug Output

[14:47:21] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/e627e516/player_ias.vflset/id_ID/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\LOQ-15~1\AppData\Local\Temp\lavaplayer-yt-player-script15280748732181509198.js
[14:47:21] [ERROR] [AudioHandler]: Track -HdxWBRV86w has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment] 2024-10-21 08:30
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-21 08:30 UTC
