### ISSUE TITLE
[Bug Report] Get this error when i try to play a song | Error loading: Sign in to confirm you're not a bot

### ISSUE THREAD

**Issue by bjarkeh14** [jagrosh/MusicBot#1605] opened 2024-07-03 09:08 UTC
### Bug Description

Error loading: Sign in to confirm you're not a bot

### Steps to Reproduce

1. Ask the bot to play
2. Error loading: Sign in to confirm you're not a bot
3. Nothing happens

### Expected Result

hope the bug et fixed

### Debug Output

Error loading: Sign in to confirm you're not a bot

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2024-07-03 09:13
Duplicate of #1588. Please check the pinned issues next time.

**Closed by MichailiK** 2024-07-03 09:13 UTC
