### ISSUE TITLE
[Bug Report] Bot not beginning to play music

### ISSUE THREAD

**Issue by TheDarkLordo** [jagrosh/MusicBot#554] opened 2020-11-02 23:47 UTC
**Describe the bug**
When I write .play "something", the bot finds it on youtube, joins the voice chat but it usually suddenly leaves from the voice channel without playing anything. The bot start playing normally when I play a playlist in txt file but sometimes it says it loaded a number of songs but they're not actually added to queue.

**To Reproduce**
1. try to play something
2. 
3. 

**Expected behavior**
Searching the title on youtube, joining the voice channel and beginning playing without disconnecting

**Screenshots**
In the screenshot, you can see that the bot loaded the music but it isn't in voice channel because it joined and suddenly disconnected. 
![Bot left voice channel without playing](https://user-images.githubusercontent.com/73529016/97931522-13291680-1d6e-11eb-8ff1-a358f24c1fab.PNG)

I also attached console screenshot
![console](https://user-images.githubusercontent.com/73529016/97931540-21773280-1d6e-11eb-8cce-55dbb7af73be.PNG)

**Debug Info**
I attached debug info
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/5478631/debug_information.txt)

**Additional context**
Playing playlists it works. But playing a song freely, it usually doesn't.

**Comment by jagrosh** [comment] 2020-11-02 23:59
Duplicate of #531

**Closed by jagrosh** 2020-11-02 23:59 UTC
