### ISSUE TITLE
[Bug Report] Prefix command

### ISSUE THREAD

**Issue by raffibaihaqy** [jagrosh/MusicBot#1250] opened 2022-11-21 12:01 UTC
### Bug Description

changing prefix command does not work other than original "@mention"

### Steps to Reproduce

1. changing prefix from config
2. start bot as usual
3. bot does not respond

### Expected Result

I expected we can change the prefix other than the original "@mention"

### Debug Output

JMusicBot-0.3.8

### Additional Info

<img width="247" alt="bug" src="https://user-images.githubusercontent.com/42157989/203047892-4c504d1e-bd5b-4f3f-bd15-17d97e8e16b9.png">

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-11-21 12:18
Duplicate of #1215

**Closed by MichailiK** 2022-11-21 12:18 UTC
