### ISSUE TITLE
[Bug Report] Bot connects to the VC when executed the command and then desconects

### ISSUE THREAD

**Issue by gamer-sans987** [jagrosh/MusicBot#1559] opened 2024-04-27 21:19 UTC
### Bug Description

When i try to use the new version, 0.4.0, everytime that i try to use the bot it just connects, says that it have the musics in the queue and then desconnects, downgrading to 0.3.9 fixes the issue

### Steps to Reproduce

1. use the command (e.g. --p Never gonna give you up)
2. the bot search the music
3. the bot founds the music and proceeds to connect the voice channel
4. after less than a second desconnects from the voice channel

### Expected Result

it should play the music, it doesnt

### Debug Output

System Properties:
  java.version = 22.0.1
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 22
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 22.0.1+8-16
  java.specification.version = 22
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.0
  Owner = 563458959818620990
  Prefix = --
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 727959e9f621fc457b3a5adafcfffb55fdeaa538-SNAPSHOT

Runtime Information:
  Total Memory = 48
  Used Memory = 26

Discord Information:
  ID = 1073947023058931792
  Guilds = 8
  Users = 6

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2024-04-27 21:57
Duplicate of #1537

**Closed by MichailiK** 2024-04-27 21:57 UTC
