### ISSUE TITLE
[Feature Request] Support multilingual

### ISSUE THREAD

**Issue by s1204IT** [jagrosh/MusicBot#1580] opened 2024-05-24 12:51 UTC
### Is your feature request related to a problem? Please describe.

Non-English languages are not supported

### What is your ideal solution to the problem?

Make it multilingual with Crowdin or Weblate, and make it possible to select the language from config.txt.

### How would this feature be used?

Use user and bot owner's language

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-07-10 14:02
Duplicate of #689

**Closed by jagrosh** 2024-07-10 14:02 UTC
