### ISSUE TITLE
Jbot is not working after java update

### ISSUE THREAD

**Issue by FreakyBeast** [jagrosh/MusicBot#1736] opened 2024-10-23 19:43 UTC
### Bug Description

The jbot is not working with vpn or without, it just keeps popping in and out of the chanel. all was fine until the java update . please help

### Steps to Reproduce

simply download new java and try running jbot

### Expected Result

I wish to have the issues fixed :)

### Debug Output

noine

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by DaanSelen** [comment] 2024-10-23 19:53
Still not fixes. Only works with Soundcloud.

**Comment by bradkroll90** [comment] 2024-10-24 00:04
I am unsure if this is related, but I have started having issues with YT playback inside of the last week. The console error is a lavalink error "Please sign in." - different than the bot confirmation error message. I am unsure if this is related or unrelated to the YT bot detection issue, and I know that oAuth2 support is already in the works for that.

I have tried both using standard releases, and also building from source with several different versions of the lavalink player, same error in all cases.

**Comment by MichailiK** [comment] 2024-10-24 06:37
You are likely facing one of two widespread issues:
- #1588
- #1682

The Java version is not the cause, it's YouTube that has recently made changes preventing third parties from loading videos. You can try running older JMusicBot versions with Java 8 to see that they are failing to play tracks too.

Closing this, as this is likely a duplicate of the two issues above.

**Closed as not planned by MichailiK** 2024-10-24 06:37 UTC

**Comment by alanman87** [comment] 2024-10-24 19:36
Why was this closed as “not planned?” Are you not planning to fix it? When will this bot be getting an update? It hasn’t worked in months!

**Comment by MichailiK** [comment] 2024-10-25 06:49
![Screenshot_20241025-084823](https://github.com/user-attachments/assets/15578000-95f7-4c24-832b-4a22d37c4970)

**Comment by alanman87** [comment] 2024-10-26 19:16
> ![Screenshot_20241025-084823](https://private-user-images.githubusercontent.com/39029839/380043035-15578000-95f7-4c24-832b-4a22d37c4970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NzAyNTgsIm5iZiI6MTcyOTk2OTk1OCwicGF0aCI6Ii8zOTAyOTgzOS8zODAwNDMwMzUtMTU1NzgwMDAtOTVmNy00YzI0LTgzMmItNGEyMmQzN2M0OTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE5MTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5N2YyZjZjOGM2NGNjZDA2NzQyZTQ5ZTg5NTBhZjBmOWQ0OWFhYWFmNTBkMGRlY2JiOWE0ZDAyMzYwNzg5MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.690NlHZ6tTVsRe56ResNDzD7CE0HfCGnL72_jp8ytNQ)

You don’t have to have a smart ass reply. As someone who doesn’t use GitHub or work with software much, it isn’t obvious that’s what it means as all that is displayed is this:

![IMG_3664](https://github.com/user-attachments/assets/f294918f-88d6-4667-9607-9fadb456aca9)

**Comment by MichailiK** [comment] 2024-10-26 19:36
> You don’t have to have a smart ass reply.

All the while you seem to have skipped over [my comment prior to closing this issue](https://github.com/jagrosh/MusicBot/issues/1736#issuecomment-2434420178) stating why I did so, and have instead thrown around questions & a statement which sound like bad faith accusations.

Once again:

1. There are two issues with playback from YouTube.
2. Both are already known and tracked:
   - #1588
   - #1682
3. This is a duplicate of the two issues above
4. There is a pull request fixing both issues:
   - #1670

A new JMusicBot version will release once that pull request gets approved & merged.
