### ISSUE TITLE
[Bug Report] Title Here 

### ISSUE THREAD

**Issue by NicoaraAlex** [jagrosh/MusicBot#1109] opened 2022-01-27 16:32 UTC
### Bug Description

BUG REPORT CONSOLE JAR FILE

### Steps to Reproduce

IDK, WHEN PLAY TRACK ON YOUTUBE

### Expected Result

Nothing happens, only the error message appears in the console, everything works

### Debug Output

                                          **///CONSOLE ERROR**

[17:40:13] [INFO] [Startup]: Loaded config from C:\Users\user\Desktop\config.txt
[17:40:14] [INFO] [JDA]: Login Successful!
[17:40:14] [INFO] [WebSocketClient]: Connected to WebSocket
[17:40:14] [INFO] [JDA]: Finished Loading!
[18:00:12] [ERROR] [LocalAudioTrackExecutor]: Error in playback of xplzEh9f-jU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 17.0.1
  java.runtime.version: 17.0.1+12-LTS-39
  java.vm.version: 17.0.1+12-LTS-39
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:116)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	... 4 common frames omitted

                                                             **///DEBUG FILE**

```
System Properties:
  java.version = 17.0.1
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 17.0.1+12-LTS-39
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.3.6
  Owner = 436555573484322827
  Prefix = ^
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.3.0_324
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 56
  Used Memory = 16

Discord Information:
  ID = 838772919705534476
  Guilds = 3
  Users = 2
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by Sanduhr32** [comment] 2022-01-27 17:07
Not success status code: 403
the youtube video is age restricted or so

**Comment by MichailiK** [comment] 2022-01-27 18:53
Duplicate of #885

**Closed by MichailiK** 2022-01-27 18:53 UTC
