### ISSUE TITLE
[Bug Report] I have this error

### ISSUE THREAD

**Issue by alketbi2123** [jagrosh/MusicBot#547] opened 2020-11-01 10:25 UTC
![Screenshot 2020-11-01 142533](https://user-images.githubusercontent.com/68159602/97800365-1c22c680-1c4e-11eb-9cbb-efce192b3ab5.png)

**Comment by MyndPhreak** [comment] 2020-11-01 13:30
Same here, fails to play most songs now. Some do still work but it's spotty.

**Comment by MichailiK** [comment] 2020-11-01 20:43
Duplicate of #531

**Closed** 2020-11-01 21:45 UTC
