### ISSUE TITLE
[Bug Report] Bot does not play music and weirdly joins and leaves channel.

### ISSUE THREAD

**Issue by EMREOYUN** [jagrosh/MusicBot#374] opened 2020-03-26 20:06 UTC
**Describe the bug**
When we use play, bot not plays and keep joins and leaves channel until we say stop.

**To Reproduce**
1. Run the bot
2. Execute play command
3. It won't play and keep joins and leaving music channel

**Expected behavior**
Should play

**Screenshots**
This isn't screenshotable behaviour.

**Debug Info**
Same with #373 

**Additional context**
Console gives no error. Bot also gives no error.

**Comment by Juxstin** [comment] 2020-03-30 07:12
Happened to me to.

**Comment by surenzxx** [comment] 2020-04-09 08:54
Also happend to me.

**Comment by jagrosh** [comment] 2020-04-09 13:23
Likely a duplicate of #370, or a related issue

**Closed by jagrosh** 2020-04-09 13:23 UTC

**Comment by EMREOYUN** [comment] 2020-04-10 07:13
@jagrosh It isn't 404 or Youtube related error. It keeps doing it when music is not playing. Not a duplicate of #370

**Comment by jagrosh** [comment] 2020-04-10 12:38
If it's repeatedly joining and leaving the voice channel nonstop when trying to play something, then it's Discord disconnecting it (and error on their end). Try changing your voice region if that happens.
