### ISSUE TITLE
[Feature Request] Add / commands

### ISSUE THREAD

**Issue by FuchsFuchs1** [jagrosh/MusicBot#1300] opened 2023-02-24 08:17 UTC
### Is your feature request related to a problem? Please describe.

I want the bot to be like every other one by supporting / commands

### What is your ideal solution to the problem?

idk i only code crappy html lol

### How would this feature be used?

/play [url/name]

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by FuchsFuchs1** [comment] 2023-02-24 08:18
totaly dont want the badge btw 😅

**Comment by jagrosh** [comment] 2023-02-24 08:24
Duplicate of #664

**Closed by jagrosh** 2023-02-24 08:24 UTC
