### ISSUE TITLE
[Bug Report] Invalid Status Code

### ISSUE THREAD

**Issue by LubricantJam** [jagrosh/MusicBot#282] opened 2019-10-10 02:39 UTC
**Describe the bug**
Simply put, trying to play a song, the bot will just join and then leave. 

**To Reproduce**
1. Play a song.
2. Bot will join and print the song with it's length.
3. Bot then leaves.

**Expected behavior**
The song is to play and function as normal.

**Version Info (please complete the following information):**
 - Operating System: Ubuntu 16.04.4 LTS
 - JMusicBot Version: 0.2.5

**Additional context**
Here's the error being reported below. The bot is only in 3 discord servers, none of which are utilizing the music element at the moment. The bot simply stopped working with no adaptations to the bot or server in any kind. 

The logging used is from PM2, hence why it differs to what you're used to. Still logs in the same way.

```
9|NexusMusic  | [03:33:59] [ERROR] [LocalAudioTrackExecutor]: Error in playback of tbvwdv385Pg
9|NexusMusic  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
9|NexusMusic  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
9|NexusMusic  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
9|NexusMusic  |         at java.lang.Thread.run(Thread.java:748)
9|NexusMusic  | Caused by: java.io.IOException: Invalid status code for video info response: 429
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.determineFailureReason(YoutubeAudioSourceManager.java:401)
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:390)
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.getTrackInfo(YoutubeAudioTrack.java:118)
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:96)
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63)
9|NexusMusic  |         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
9|NexusMusic  |         ... 4 common frames omitted

```

**Comment by jagrosh** [comment] 2019-10-10 03:53
The issue is that Toutube is ratelimiting the bot, and there isn't anything that can be fixed on my end to prevent this. Is there anything else running on the VPS or same IP address as this bot? Where is it being hosted?

**Comment by LubricantJam** [comment] 2019-10-10 11:43
No sir, it was working perfectly fine for a solid few months. I can try closing down all additional bots and see if that causes an issue but as far as I'm aware, none use lavaplayer (RedBot does, but the audio module is disabled).

This is running off my dedicated machine which I've been using your bot on for a good year now. For some reason, it just clogged up and stopped working. I'll do some slight more debugging and get back to you but it's very odd how it just decided to stop working.

**Comment by LubricantJam** [comment] 2019-10-10 12:04
Yeah, I turned all other instances of a discord bot offline and it still has the issue. Is there such thing of a cooldown with YouTube where it's been rate limited so much that it just needs to sit idle/offline? I'm unsure as how this occurred as nothing has changed.

**Comment by Dragonblitz10** [comment] 2019-10-12 22:36
youtube is being more aggressive and are rate limiting music bots so its more likely that.

**Comment by MichailiK** [comment] 2019-10-14 10:57
Yes. Large music bots such as Rythm can't play anything from YouTube anymore due to these rate limits YouTube recently put.

**Comment by jagrosh** [comment] 2019-10-23 20:05
Closing as I'm centralizing all issues related to this in #305

**Closed by jagrosh** 2019-10-23 20:05 UTC
Labels: lavaplayer
