### ISSUE TITLE
[Bug Report] Bot cant play music

### ISSUE THREAD

**Issue by Asynchronouss** [jagrosh/MusicBot#1723] opened 2024-10-16 13:30 UTC
### Bug Description

The bot logs in successfully, but when I type a command in Discord, it joins the voice channel and then leaves immediately

### Steps to Reproduce

1. bot join voice channel
2. bot leave.

### Expected Result

play music

### Debug Output

[20:48:05] [INFO] [JDA]: Login Successful!
[20:48:05] [INFO] [WebSocketClient]: Connected to WebSocket
[20:48:06] [INFO] [JDA]: Finished Loading!
[20:48:26] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/815edc2a/player_ias.vflset/zh_TW/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\Z600\AppData\Local\Temp\lavaplayer-yt-player-script12550364013788378634.js
[20:48:26] [ERROR] [AudioHandler]: Track PnkzS7sIlpU has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by SquareDonut1** [comment] 2024-10-16 18:01
im getting the same error

**Comment by officialtroller** [comment] 2024-10-16 18:36
#1682 

You have NOT searched for similar issues lol

**Comment by MichailiK** [comment] 2024-10-16 20:21
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-16 20:21 UTC
