### ISSUE TITLE
[Feature Request] Command Recommendation when prefix is added in Discord Chat

### ISSUE THREAD

**Issue by Planellas6** [jagrosh/MusicBot#1441] opened 2023-10-06 06:23 UTC
### Is your feature request related to a problem? Please describe.

Hello, I have added this bot to some of my servers, and some of my friends are often confused about the bot's command, and I often have to direct them to the /help command which is tedious.

### What is your ideal solution to the problem?

My solution to this would be to implement some kind of command recommendations like other bots have when you type for example "/" recommends commands from the bot that start with the prefix and the letter ex: "/p" would recommend /play, /playlist. ETC. 

### How would this feature be used?

1: To increase ease of use
2: Dummy proof the use of this bot in servers with many bots
3: Increase enjoyment of using the bot

### Additional Info

 I know nitpicky request. the bot works like a charm and this isn't a major concern for most people but it would be a nice implementation seeing as most other mainstream music bots offer this sort of implementation, I could see why something minor like this may not be high on the developer's to-do list since it is mainly just an ease of use thing but I would like to see it and some of my other friends who have added this bot to their servers would also like to see command recommendations as many of us rarely request songs or use many of the commands until we have to then we have to refer to /help... I know first-world problems haha. Anyway I appreciate the good work, and I would love to see this get added in the future, keep up the good work developers!

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2023-10-06 08:08
Duplicate of #664

**Closed by MichailiK** 2023-10-06 08:08 UTC
