### ISSUE TITLE
[Bug Report] Many Youtube Videos no longer play that used to

### ISSUE THREAD

**Issue by Djinnistorm** [jagrosh/MusicBot#420] opened 2020-05-29 03:15 UTC
Attempt to play a video, either by search or url, and the video correctly enters queue but does not play. Video will be skipped in the queue entirely. Over the course of quarantine more and more videos have become unplayable...or at least more have been noticed. My best guess is youtube made yet another change that broke lavaplayer.

**To Reproduce**
Play certain youtube videos, many of which have worked earlier in this particular bot version. I assume a youtube change has broken lavaplayer. again. ugh.
Some example videos, and yes they're almost all memes. Don't judge my discord. https://www.youtube.com/watch?v=ZZ5LpwO-An4
https://www.youtube.com/watch?v=RxgdaMZRgRo
https://www.youtube.com/watch?v=FzAb8rVqDkY
https://www.youtube.com/watch?v=HgzGwKwLmgM
https://www.youtube.com/watch?v=YOBpATa1HUY

All of these have been played successfully before at least within a few months, if not on this exact bot version. None of them play now, and plenty more. 

**Expected behavior**
Videos to play. 

**Debug Info**
```
System Properties:
  java.version = 1.8.0_251
  java.vm.name = Java HotSpot(TM) Client VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_251-b08
  java.specification.version = 1.8
  os.arch = x86
  os.name = Windows 10

JMusicBot Information:
  Version = 0.2.8
  Owner = 182299753281880065
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.46

Runtime Information:
  Total Memory = 22
  Used Memory = 20

Discord Information:
  ID = 417380432053796874
  Guilds = 2
  Users = 12
```

Console Output: 
```
[23:04:04] [INFO] [Startup]: Loaded config from C:\Users\Marc\Documents\MusicBot\config.txt
[23:04:04] [INFO] [JDA]: Login Successful!
[23:04:04] [INFO] [WebSocketClient]: Connected to WebSocket
[23:04:04] [INFO] [JDA]: Finished Loading!
[23:04:45] [ERROR] [LocalAudioTrackExecutor]: Error in playback of ZZ5LpwO-An4
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	... 4 common frames omitted

```

**Comment by jagrosh** [comment] 2020-05-29 03:15
Duplicate of #417

**Closed by jagrosh** 2020-05-29 03:15 UTC

**Comment by Djinnistorm** [comment] 2020-05-29 03:18
Hmm, thought it was different from the start of the error but closer inspection shows them to be basically the same. My mistake.
