### ISSUE TITLE
[Feature Request] Bass Boost

### ISSUE THREAD

**Issue by HansDerechte** [jagrosh/MusicBot#1463] opened 2023-12-22 19:46 UTC
### Is your feature request related to a problem? Please describe.

You can give music even more vibe 

### What is your ideal solution to the problem?

A bass boost function 

### How would this feature be used?

1.Your command for the bot and then the level of the boost 1-150

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2023-12-22 21:26
Duplicate of #968

**Closed by MichailiK** 2023-12-22 21:26 UTC
