### ISSUE TITLE
[Bug Report] Error loading track

### ISSUE THREAD

**Issue by sergiustaicu** [jagrosh/MusicBot#515] opened 2020-10-16 22:53 UTC
**Describe the bug**
error loading track from yt music, used to work before the latest update

**To Reproduce**
1. Run JMusicBot-0.2.10.jar
2. Use command '
-play https://music.youtube.com/watch?v=xj-izU6w7S4&list=RDAMVMDuQGokwsWF8'
3. Error loading track

**Expected behavior**
play the selected playlist

**Screenshots**

https://cdn.discordapp.com/attachments/560049783281156106/766795191750230057/unknown.png

**Debug Info**
```
System Properties:
  java.version = 10.0.2
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 10
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 10.0.2+13
  java.specification.version = 10
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.2.10
  Owner = 236924644563746816
  Prefix = @mention
  AltPrefix = -
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.50

Runtime Information:
  Total Memory = 256
  Used Memory = 52

Discord Information:
  ID = 708685589045837945
  Guilds = 1
  Users = 148
```

**Additional context**

**Comment by lordbinchicken** [comment] 2020-10-23 19:06
this is an issue with lavaplayer, it's being patched in the next update of MusicBot

**Comment by jagrosh** [comment] 2020-10-23 19:34
Duplicate of #520 (closing this one as it has less info)

**Closed by jagrosh** 2020-10-23 19:34 UTC
