### ISSUE TITLE
[Bug Report] Wont play some songs

### ISSUE THREAD

**Issue by SpaceXLiquid** [jagrosh/MusicBot#548] opened 2020-11-01 10:55 UTC
**Describe the bug**
JMusicBot doesnt play some certain songs like **Pixel Galaxy** and it wont hold the queue.

**To Reproduce**
Steps to reproduce not playing issue:
1. Play **Pixel Galaxy** song

**Expected behavior**
Playing the exact song

**Comment by MichailiK** [comment] 2020-11-01 20:44
Likely duplicate of #531

**Closed** 2020-11-01 21:45 UTC
