### ISSUE TITLE
[Bug Report] Unable to play YouTube tracks

### ISSUE THREAD

**Issue by midspam** [jagrosh/MusicBot#383] opened 2020-04-09 16:07 UTC
**Describe the bug**
When given a YouTube track, the bot comes into the channel, loads the track but is unable to play it and leaves.

**To Reproduce**
1. Play command with any YouTube tracks.

**Expected behavior**
Bot comes into the channel. Loads the track. Leaves the channel without playing it.

**Screenshots**
![](https://i.imgur.com/WkzJbXR.png)

**Debug Info**
Windows 10

**Comment by jagrosh** [comment] 2020-04-09 16:09
Duplicate of #370

**Closed by jagrosh** 2020-04-09 16:09 UTC
