### ISSUE TITLE
[Bug Report] Bot joins channel, does not have any input then leaves channel (YouTube link)

### ISSUE THREAD

**Issue by ItsKewan** [jagrosh/MusicBot#1187] opened 2022-06-22 17:59 UTC
### Bug Description

When the user wants to play a song from this YouTube link _https://www.youtube.com/watch?v=9z8lSarGIuY_ , the bot is able to join after the correct input. However, does not "play" any sound and subsequently leaves the channel after .75 seconds.

![4583b235ae06951fde63af954c6d79f3](https://user-images.githubusercontent.com/108022081/175105356-621473c0-d962-40b6-95f3-c677f9f6953d.gif)

### Steps to Reproduce

1.) Type/paste !play https://www.youtube.com/watch?v=9z8lSarGIuY
2.) The bot joins the correct channel
3.) The bot does not light up as intended when detecting voice/sound input. 
4.) The bot leaves the channel after .75 seconds

### Expected Result

The song would play as if the link were a link from Soundcloud.

**For Example:**
https://soundcloud.com/twofriendsbigbootie/bb16

### Debug Output

[log2.txt](https://github.com/jagrosh/MusicBot/files/8960220/log2.txt)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2022-06-22 18:08
Duplicate of #1026

**Closed by MichailiK** 2022-06-22 18:08 UTC
