### ISSUE TITLE
[Bug Report] Keeps skipping songs in the queue

### ISSUE THREAD

**Issue by DaniWinter** [jagrosh/MusicBot#415] opened 2020-05-25 19:21 UTC
**Describe the bug**
The bot keeps skipping songs that are in the queue, a lot of the times it just skips to the end of the queue (even when there are like 10 songs queued up).

**To Reproduce**
Add a few songs to the queue or a playlist.

**Expected behavior**
Obey the queue.

**Debug Info**
```
System Properties:
  java.version = 1.8.0_252
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_252-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.8
  Owner = 303614373073649665
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.46

Runtime Information:
  Total Memory = 58
  Used Memory = 25

Discord Information:
  ID = 704278753009860668
  Guilds = 1
  Users = 62
```

**Comment by jagrosh** [comment] 2020-05-25 19:24
Can't really help without logs, but I'm nearly certain that this will be a duplicate of #305

**Closed by jagrosh** 2020-05-25 19:24 UTC
