### ISSUE TITLE
[Bug Report] Not success status code: 403 hasn't been fixed

### ISSUE THREAD

**Issue by Ihatediscordbots** [jagrosh/MusicBot#1639] opened 2024-08-02 18:28 UTC
### Bug Description

Exactly as title states

### Steps to Reproduce

1. Start up the .jar file
2. Run the 'play' command
3. bot joins and does nothing

### Expected Result

Bot to play the attached link, as it has done before
https://youtu.be/zcQvAy3oi0E?si=-YdQRWz14GqA7Ij4

### Debug Output

```
System Properties:
  java.version = 22.0.2
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 22
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 22.0.2+9-70
  java.specification.version = 22
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.2
  Owner = 566705395230572554
  Prefix = $
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 120
  Used Memory = 39

Discord Information:
  ID = 1268991213055512576
  Guilds = 1
  Users = 2
```

### Additional Info

Console output

[15:48:24] [INFO] [JMusicBot]: Loaded config from C:\Users\(my name)\Documents\1 music bot\config.txt
[15:48:25] [INFO] [JDA]: Login Successful!
[15:48:25] [INFO] [JMusicBot]: JMusicBot
[15:48:26] [INFO] [WebSocketClient]: Connected to WebSocket
[15:48:26] [INFO] [JDA]: Finished Loading!
[15:48:34] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/d2e656ee/player_ias.vflset/en_GB/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\(my name)\AppData\Local\Temp\lavaplayer-yt-player-script339459793929780264.js
[15:48:36] [ERROR] [LocalAudioTrackExecutor]: Error in playback of zcQvAy3oi0E
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	... 4 common frames omitted
[15:48:36] [ERROR] [AudioHandler]: Track zcQvAy3oi0E has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	... 4 common frames omitted

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

4.2

**Comment by HelloWorldGoodByeWorld123** [comment] 2024-08-02 23:39
Hurry up Jarosh, I need my bot. Somebody call this dood up and tell him, the whole bot community need him to hurry up and fix this bot. Thank you

**Comment by jam-lock** [comment] 2024-08-03 00:06
For any one running into this issue, I managed to get it working with the version update from https://github.com/jagrosh/MusicBot/commit/e6bfd1841f4342240ff830b393bbe719e6f1bbe3.

Download the source code
`git clone https://github.com/jagrosh/MusicBot/`

Install mvn
`sudo apt install maven`

Build the project
`mvn install`

You should have your .jar file at /target/JMusicBot-Snapshot-All.jar

**Comment by MoNoLidThZ** [comment] 2024-08-03 12:40
Duplicate of #1630 and #1637

I have setup Jenkins for jMusicBot on my own server that pulls code from this repo and compiles them into jar automatically, so anyone with less technical expertise can download development builds on mine [here](https://ci.nekohost.cloud/job/JMusicBot/).

Just only a warning that this version isn't supported by the dev and the auto-update notify will keeps nagging you to update to broken version of 0.4.2 so workaround is turn of update check until jargosh made a stable release.

@HelloWorldGoodByeWorld123 feel free to use my builds of the bot if you needed them immediately.

**Comment by mindleak** [comment] 2024-08-04 04:57
> For anyone running into this issue, I managed to get it working with the version update from [e6bfd18](https://github.com/jagrosh/MusicBot/commit/e6bfd1841f4342240ff830b393bbe719e6f1bbe3).
> 
> Download the source code `git clone https://github.com/jagrosh/MusicBot/`
> 
> Install mvn `sudo apt install maven`
> 
> Build the project `mvn install`
> 
> You should have your .jar file at /target/JMusicBot-Snapshot-All.jar

I can confirm this worked for me as well. Thank you for the suggestion!

Though as @MoNoLidThZ noted, it does nag you to update from "Snapshot" to "0.4.2"

**Comment by ubsadmin** [comment] 2024-08-04 21:48
> Duplicate of #1630 and #1637
> 
> I have setup Jenkins for jMusicBot on my own server that pulls code from this repo and compiles them into jar automatically, so anyone with less technical expertise can download development builds on mine [here](https://ci.nekohost.cloud/job/JMusicBot/).
> 
> Just only a warning that this version isn't supported by the dev and the auto-update notify will keeps nagging you to update to broken version of 0.4.2 so workaround is turn of update check until jargosh made a stable release.
> 
> @HelloWorldGoodByeWorld123 feel free to use my builds of the bot if you needed them immediately.

This one worked for me Any one whos trying to use it please download the snapshot-all.jar it will work.

**Comment by ubsadmin** [comment] 2024-08-04 21:56
> For anyone running into this issue, I managed to get it working with the version update from [e6bfd18](https://github.com/jagrosh/MusicBot/commit/e6bfd1841f4342240ff830b393bbe719e6f1bbe3).
> 
> Download the source code `git clone https://github.com/jagrosh/MusicBot/`
> 
> Install mvn `sudo apt install maven`
> 
> Build the project `mvn install`
> 
> You should have your .jar file at /target/JMusicBot-Snapshot-All.jar

I tried this one as well had to install maven manually on my Windows system but somehow I get it to work even tried changing the maven version to 3.8.8 to 3.8.9 and getting an error during compiling I might have done something wrong though. if someone can help that would be great 

`C:\Users\userName\MusicBot>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< com.jagrosh:JMusicBot >------------------------
[INFO] Building JMusicBot Snapshot
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from jitpack.io: https://jitpack.io/com/github/jagrosh/JLyrics/master-SNAPSHOT/maven-metadata.xml
Downloaded from jitpack.io: https://jitpack.io/com/github/jagrosh/JLyrics/master-SNAPSHOT/maven-metadata.xml (383 B at 644 B/s)
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ JMusicBot ---
[INFO] Deleting C:\Users\Uzee\MusicBot\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ JMusicBot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ JMusicBot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 69 source files to C:\Users\UserName\MusicBot\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.796 s
[INFO] Finished at: 2024-08-04T16:50:03-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project JMusicBot: Fatal error compiling: invalid target release: 11 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by jagrosh** [comment] 2024-08-05 20:43
Duplicate

**Closed by jagrosh** 2024-08-05 20:43 UTC
