### ISSUE TITLE
[Bug Report] Constant ratelimiting

### ISSUE THREAD

**Issue by Speak2Erase** [jagrosh/MusicBot#414] opened 2020-05-24 21:06 UTC
**Describe the bug**
I recently set up a music bot using this software, but just now, it's getting constant rate-limiting from youtube. Currently, it is flooding my console with 
`[13:56:55] [ERROR] [LocalAudioTrackExecutor]: Error in playback of qKMsgu9NIa8
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:28)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:75)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
        ... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video page response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:39)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:26)
        ... 7 common frames omitted` and my channel description is out of wack.

**To Reproduce**
No clue. I have a lot of playlists and a default playlist on 2 servers, which may relate, but the video id's that it's getting ratelimited for aren't the default playlists.

**Expected behavior**
For the bot to run smoothly.
**Screenshots**

**Debug Info**
Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, JMusicBot version, etc.
`
System Properties:
  java.version = 1.8.0_241
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_241-b07
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.2.8
  Owner = 351871502460649485
  Prefix = ^
  AltPrefix = *
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.46

Runtime Information:
  Total Memory = 176
  Used Memory = 33

Discord Information:
  ID = 713069493475344414
  Guilds = 2
  Users = 81
`
**Additional context**
The only thing that could be related is me installing eclipse ide and openjdk yesterday.

**Comment by jagrosh** [comment] 2020-05-24 21:12
Duplicate of #305

**Closed by jagrosh** 2020-05-24 21:12 UTC
