### ISSUE TITLE
[Bug Report] Can’t queue by song name

### ISSUE THREAD

**Issue by redbrain** [jagrosh/MusicBot#450] opened 2020-07-02 05:05 UTC
**Describe the bug**
I can’t queue a song by name. Using a URL works fine.

**To Reproduce**
1. Host the bot. 
2. Run `!play [song name]`

**Expected behavior**
The bot will attempt to load the song and return “not found”

**Screenshots**
![792F3AC2-5128-440F-8C44-AFAC07164767](https://user-images.githubusercontent.com/42494361/86318358-b969e180-bbff-11ea-92b9-9c8bc5c73a78.png)

**Debug Info**
System Properties:
  java.version = 14.0.1
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 14
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 14.0.1+7
  java.specification.version = 14
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.2.9
  Owner = 472209655536287755
  Prefix = !
  AltPrefix = @mention
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = true
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.49

Runtime Information:
  Total Memory = 49
  Used Memory = 23

Discord Information:
  ID = 716131897603915806
  Guilds = 1
  Users = 12

**Additional context**
Running multiple JDA bots on this machine.

**Comment by jagrosh** [comment] 2020-07-02 05:10
Duplicate of #443

**Closed by jagrosh** 2020-07-02 05:10 UTC
