### ISSUE TITLE
No search results found for any music

### ISSUE THREAD

**Issue by ThreeLineSolutions** [jagrosh/MusicBot#454] opened 2020-07-04 02:05 UTC
No search results found for any music when I use the play command.

**Comment by iRealKsA** [comment] 2020-07-04 08:23
Me too

**Comment by DJEnderblue** [comment] 2020-07-04 09:31
I third this

**Comment by djsmithuk** [comment] 2020-07-04 09:44
Updating the pom.xml file to use a newer version of larval-layer 1.3.50 then compile, worked for myself

**Comment by DJEnderblue** [comment] 2020-07-04 10:39
> Updating the pom.xml file to use a newer version of lavaplayer 1.3.50 then compile, worked for myself

could you explain this? or give me the finished java file? I am not so tech experienced to do it myself

**Comment by Sanduhr32** [comment] 2020-07-04 14:25
Building JMusicbot yourself is not supported. Always use the official releases on github.
This issue also is a duplicate of #443.

**Comment by jagrosh** [comment] 2020-07-04 15:43
Duplicate of #443

**Closed by jagrosh** 2020-07-04 15:43 UTC
