### ISSUE TITLE
[Feature Request] Allow all songs.

### ISSUE THREAD

**Issue by richard1234YT** [jagrosh/MusicBot#347] opened 2020-02-03 22:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Allow people to play any songs they like.
2. Have an config file to change it.
3. This will be easier for people.

**Additional context**
The reason is because lately, clean songs are getting stopped due to bad language. But I check and their is none.

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1

**Comment by jagrosh** [comment] 2020-02-04 20:33
This appears to be a duplicate of #336

**Closed by jagrosh** 2020-02-04 20:33 UTC
