### ISSUE TITLE
Bot automatically disconnects

### ISSUE THREAD

**Issue by glisovic01** [jagrosh/MusicBot#1739] opened 2024-10-25 19:09 UTC
### Bug Description

The bug is that the bot just automatically disconnects from voice instead of playing.

### Steps to Reproduce

1. Writing "!play <song-name>"

### Expected Result

I expected the bot to play music...

### Debug Output

20:49:36] [INFO] [JDA]: Login Successful!
[20:49:36] [INFO] [JMusicBot]: JMusicBot
[20:49:36] [INFO] [WebSocketClient]: Connected to WebSocket
[20:49:36] [INFO] [JDA]: Finished Loading!
[20:49:41] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/fb725ac8/player_ias.vflset/sr_RS/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\DaVinci\AppData\Local\Temp\lavaplayer-yt-player-script5630556909074593793.js
[20:49:42] [ERROR] [AudioHandler]: Track _n986j3N_mw has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
	at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment] 2024-10-25 19:12
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-25 19:12 UTC
