### ISSUE TITLE
[Bug Report] [ERROR] [SignatureCipherManager]: Problematic YouTube player script

### ISSUE THREAD

**Issue by ghost** [jagrosh/MusicBot#1694] opened 2024-09-24 23:16 UTC
### Bug Description

Bot joins call but fails to play audio when prompted.

### Steps to Reproduce

1) Launch bot with command character and youtube link
3) Bot fails to join and produces error in console

### Expected Result

I expected the bot to queue and play audio when prompted.

### Debug Output

Console Dump:
[18:01:32] [INFO] [JMusicBot]: Loaded config from S:\Admin\Documents\JMusicBot\config.txt
[18:01:33] [INFO] [JDA]: Login Successful!
[18:01:33] [INFO] [WebSocketClient]: Connected to WebSocket
[18:01:33] [INFO] [JMusicBot]: JMusicBot
[18:01:33] [INFO] [JDA]: Finished Loading!
[18:01:49] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/c9dd45ed/player_ias.vflset/en_US/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\Admin\AppData\Local\Temp\lavaplayer-yt-player-script13360609526194135674.js
[18:01:51] [ERROR] [LocalAudioTrackExecutor]: Error in playback of aByspCEjdV4
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	... 4 common frames omitted
[18:01:51] [ERROR] [AudioHandler]: Track aByspCEjdV4 has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	... 4 common frames omitted

### Additional Info

S drive used as partition from C drive where I run my OS. I've had no issues with this previously. Curious if this may be an issue with different java versions installed as I have multiple for various programs.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by editspace** [comment] 2024-09-24 23:20
I get the same error but after retrying a couple times i get `[00:19:01] [INFO] [JMusicBot]: Loaded config from /home/rasberrypi/Documents/ambermusic/config.txt
[00:19:01] [INFO] [Settings]: serversettings.json loaded from /home/rasberrypi/Documents/ambermusic/serversettings.json
[00:19:02] [INFO] [JDA]: Login Successful!
[00:19:02] [INFO] [JMusicBot]: JMusicBot
[00:19:02] [INFO] [WebSocketClient]: Connected to WebSocket
[00:19:02] [INFO] [JDA]: Finished Loading!
[00:19:11] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/c9dd45ed/player_ias.vflset/en_US/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script6151610150491238365.js
[00:19:11] [ERROR] [AudioHandler]: Track K0HSD_i2DvA has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Sign in to confirm you’re not a bot
        at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by Eggrens** [comment] 2024-09-24 23:50
Having the same issue here on Xubuntu. Was working fine a couple days ago but now won't play anything because of this error

**Comment by livehifi** [comment] 2024-09-25 00:23
Same issue here, unraid docker.

**Comment by alanman87** [comment] 2024-09-25 00:42
same issue here, ubuntu 22.04 docker

**Comment by Phishing-Fish** [comment] 2024-09-25 00:49
Same here!

**Comment by Strophie** [comment] 2024-09-25 02:28
Same here, on Kubuntu 24.04.1

**Comment by Ashnard** [comment] 2024-09-25 03:46
same here, xubuntu

**Comment by memomomode** [comment] 2024-09-25 03:49
any chance you were trying to play episode three of the talk tuah podcast?

**Comment by saamimansoor** [comment] 2024-09-25 10:48
same issue here, windows 10 pro

**Comment by Kajek777** [comment] 2024-09-25 15:40
same here

**Comment by Kalium919** [comment] 2024-09-25 20:11
same here

**Comment by bobbydanieljones** [comment] 2024-09-25 21:13
same here

**Comment by ThePowerOfElectricity** [comment] 2024-09-26 10:09
> same here but this fixed it for me. just re jar it afterwards and use it instead [33b91f9](https://github.com/jagrosh/MusicBot/commit/33b91f98fc6c50e5e9c1c108320306c6029d2360)

For the folks who have no idea what you did to get it working... How do we work your magic?

**Comment by TheeSkengdo** [comment] 2024-09-26 14:19
> same here but this fixed it for me. just re jar it afterwards and use it instead [33b91f9](https://github.com/jagrosh/MusicBot/commit/33b91f98fc6c50e5e9c1c108320306c6029d2360)

Which folder is the pom file located in?

**Comment by bobbydanieljones** [comment] 2024-09-26 14:49
you can download the source code. the pom file is there. once you change the library version in the pom just reload maven and then jar it again then replace your old jar with the new jar. youll get an update warning but you can ignore it until they update it

**Comment by Kajek777** [comment] 2024-09-26 14:51
can someone just send the jar that actually works? i don't know how to use maven and all that stuff

**Comment by TheeSkengdo** [comment] 2024-09-26 14:54
> can someone just send the jar that actually works? i don't know how to use maven and all that stuff

https://github.com/xPrinny/MusicBot/releases

**Comment by derDeidra** [comment] 2024-09-26 22:38
Using the above fixed it for me, hopefully can get updated in the main repo soon

**Comment by Callumpy** [comment] 2024-09-28 18:03
Dockerised version using xPrinny's fork for fellow lazy people: https://hub.docker.com/r/callumpy/discord-musicbot

`latest` has their forked jar file.

**Comment by DaanSelen** [comment] 2024-09-29 13:17
Same on Kubernetes

**Comment by neercsys** [comment] 2024-09-29 15:50
I have the same problem. I'm using jmusicbot via a docker craumix/jmusicbot

**Comment by dudefoxlive** [comment] 2024-10-01 03:28
So is there not going to just be a new release of the jar file? I am using yojoshb/jmusicbot-docker for my docker container and it simply just querys for the latest version and downloads the jar on each launch. I would prefer to just keep things as they are.

**Comment by MichailiK** [comment] 2024-10-01 08:24
As this is a duplicate of #1682 & for consodilation purposes, we will continue tracking this issue there. Additionally, a fix for this & a similar issue is currently in the works:

- #1670

**Closed as not planned by MichailiK** 2024-10-01 08:24 UTC

**Comment by lainq** [comment] 2024-12-26 16:09
I got it working after I updated lavaplayer and lavalink-youtube-source in pom.xml to the latest version.

**Comment by Zer0o2** [comment] 2025-02-05 17:27
@lainq can u give us a tuturial how to do it, that would be awsome

**Comment by dudefoxlive** [comment] 2025-02-05 17:29
Just download the latest jar file from the discord. saves you a lot of time and a headache

**Comment by Zer0o2** [comment] 2025-02-05 17:33
do you mybe have the discord link?

**Comment by dudefoxlive** [comment] 2025-02-05 17:37
> do you mybe have the discord link?

Its in the readme page but here is the link **https://discord.com/invite/0p9LSGoRLu6Pet0k**

**Comment by Zer0o2** [comment] 2025-02-05 17:45
Legend
