### ISSUE TITLE
[Bug Report] Youtube links doesn't work at all

### ISSUE THREAD

**Issue by Hax165** [jagrosh/MusicBot#382] opened 2020-04-09 14:11 UTC
**Describe the bug**
When trying to play songs from youtube, it fails and gives an error message.
Soundcloud links works fine.

**To Reproduce**
Use the play command followed by a link to a youtube video.

**Debug Info**
[14:05:39] [ERROR] [LocalAudioTrackExecutor]: Error in playback of j0h2u87JwyA
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Received non-success response code 404
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
... 4 common frames omitted

**Comment by jagrosh** [comment] 2020-04-09 14:11
Duplicate of #370

**Closed by jagrosh** 2020-04-09 14:11 UTC

**Comment by Hax165** [comment] 2020-04-09 14:13
Keep in mind that this started happening today. Worked perfectly previously.

**Comment by jagrosh** [comment] 2020-04-09 14:14
Yes it is the same issue, YouTube has been changing things frequently recently, this exact issue popped up a bit ago and then YouTube reverted the change and the bot worked again.

**Comment by Hax165** [comment] 2020-04-09 14:15
I see. Nice to know you are aware of it!
