### ISSUE TITLE
[Bug Report] Bot joins the VC then leaves instantly

### ISSUE THREAD

**Issue by 0Atrox0** [jagrosh/MusicBot#556] opened 2020-11-04 05:38 UTC
**Describe the bug**
I go to play any song and it will join the voice chat then leave it as soon as it starts playing music.

**To Reproduce**
1. Request a song.

**Console Message**
```
[21:32:17] [INFO] [Startup]: Loaded config from C:\Users\atrox\Desktop\Musicbot\config.txt
[21:32:17] [INFO] [JDA]: Login Successful!
[21:32:18] [INFO] [WebSocketClient]: Connected to WebSocket
[21:32:18] [INFO] [JDA]: Finished Loading!
[21:32:35] [ERROR] [LocalAudioTrackExecutor]: Error in playback of gGLebmo6oNM
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:136)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	... 4 common frames omitted
```
The console says that when I request a song.

**Debug Info**
```
System Properties:
  java.version = 1.8.0_271
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_271-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Windows Server 2012 R2

JMusicBot Information:
  Version = 0.3.1
  Owner = 295189350302613506
  Prefix = &
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_212
  JDA-Utilities Version = 3.0.4
  Lavaplayer Version = 1.3.59

Runtime Information:
  Total Memory = 241
  Used Memory = 37

Discord Information:
  ID = 761809955622748171
  Guilds = 2
  Users = 6
```

**Comment by mooseh** [comment] 2020-11-04 09:51
Exactly the same issue, I cannot play a single youtube track, even more annoyingly when i try to rollback to 0.2 where it was working fine, it not gets stuck in "loading..." state.

**Comment by MichailiK** [comment] 2020-11-04 09:52
Duplicate of #531

**Closed** 2020-11-04 11:51 UTC
