### ISSUE TITLE
[Bug Report] "Please sign in" error when trying to play YouTube video

### ISSUE THREAD

**Issue by byKeksYT** [jagrosh/MusicBot#1731] opened 2024-10-20 12:15 UTC
### Bug Description

When I try to play a video from YouTube with the bot, it connects and then disconnects shortly after. In the console I get the following error message:
```
[11:57:54] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/e627e516/player_ias.vflset/de_DE/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script9148211546117290028.js
[11:57:54] [ERROR] [AudioHandler]: Track laRwQmcXYik has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:74)
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
### Steps to Reproduce

1. Start the bot normally using the command provided on the [setup page](https://jmusicbot.com/setup/) (`java -Dnogui=true -jar JMusicBot-X.Y.Z.jar`)
2. Use the `play` command to play a YouTube video either with the direct link or the name of the video
3. The bot connects and disconnects shortly after, without playing anything in the channel

### Expected Result

I expected the bot to play the YouTube video I wanted it to play.

### Debug Output

```
System Properties:
  java.version = 11.0.24
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.24+8-adhoc.root.jdk11u
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.4.3
  Owner = 290092509885890581
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 126
  Used Memory = 25

Discord Information:
  ID = 871865539935469619
  Guilds = 3
  Users = 6
```

### Additional Info

System Info:

OS: Ubuntu 24.04.1 LTS
CPU: AMD EPYC 7443P (4 cores)
Virtualization: KVM

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment] 2024-10-20 12:34
Duplicate of #1588

**Closed as not planned by MichailiK** 2024-10-20 12:34 UTC
