### ISSUE TITLE
[Feature Request] Allow us to select which sources are allowed on the bot.

### ISSUE THREAD

**Issue by njezi** [jagrosh/MusicBot#1619] opened 2024-07-16 20:45 UTC
### Is your feature request related to a problem? Please describe.

I can play music from cdn.discordapp.com and other pages, which I do not want people to use, and there should be a way to select which sources are allowed on the bot.

### What is your ideal solution to the problem?

Add a way to disable certain sources inside of the config.json file.
There should be a list of all supported sources, with true or false, for example:
youtube=true
soundcloud=true
twitch=true
local=false
http=false

### How would this feature be used?

1. Go into the config.json file
2. In the list of sources, enable the ones you want with true, and disable the ones you don't with false.

### Additional Info

Writing this, because I'm worried about IP addresses being leaked, when requesting the bot to play a HTTP URL stream.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment] 2024-08-01 13:03
Duplicate of #808

**Closed by jagrosh** 2024-08-01 13:03 UTC
