### ISSUE TITLE
[Bug Report] Automatic song skips

### ISSUE THREAD

**Issue by mawen-fn** [jagrosh/MusicBot#1387] opened 2023-06-09 18:02 UTC
### Bug Description

The bot will skip songs automatically when multiple songs are in queue. Happens mostly when I am alone with the bot, occasionally happened with multiple people requesting songs too.

### Steps to Reproduce

1. Request a song (file or YT link)
2. Request more songs (file or YT link)

### Expected Result

The songs should play back like they are in the queue.

### Debug Output

```
System Properties:
  java.version = 11.0.18
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.18+10-post-Ubuntu-0ubuntu122.04
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.9
  Owner = 615294935242899486
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 380
  Used Memory = 56

Discord Information:
  ID = 968253751263625236
  Guilds = 1
  Users = 2
```

### Additional Info

Could it be associated with the fair queue function?

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment] 2023-06-09 18:13
Likely duplicate of #885

**Comment by jagrosh** [comment] 2024-01-31 15:34
Without logs showing the errors that happened at skip time it's impossible to debug this

**Closed by jagrosh** 2024-01-31 15:34 UTC
