### ISSUE TITLE
[Bug Report] Title Here 

### ISSUE THREAD

**Issue by Dr3awi11** [jagrosh/MusicBot#1307] opened 2023-03-01 17:59 UTC
The bot is not working Bug Description

The Bot is keep disconnecting in channels... 
and it doesn't turn on any music 
is there a new update for it  or something which made it like this???????

### Steps to Reproduce

i am trying to find a solution 

### Expected Result

.

### Debug Output

System Properties:
  java.version = 1.8.0_242
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_242-b08
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.8
  Owner = 328339724613976064
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.0_352
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 61
  Used Memory = 21

Discord Information:
  ID = 1079473844785512448
  Guilds = 1
  Users = 3
```

### Additional Info

_No response_

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by Nicolas-GE** [comment] 2023-03-01 18:12
dupe of #1306

**Comment by farrelstw** [comment] 2023-03-01 18:40
The owner said before this is some bug, you can see the post before. I also experienced same problem too, so all we can do is wait for good news from the owner

**Closed** 2023-03-01 19:39 UTC
