### ISSUE TITLE
Bot isnt working

### ISSUE THREAD

**Issue by sailesh10115** [jagrosh/MusicBot#386] opened 2020-04-09 22:51 UTC
Whenever I play the bot doesnt do anything it says it adds to queue but then when I do ?queue nothing comes up.

**Comment by Juxstin** [comment] 2020-04-09 22:54
Yea, It's not playing music idk why plays 10 seconds videos tho

**Comment by jagrosh** [comment] 2020-04-09 23:04
Duplicate of #370

**Closed by jagrosh** 2020-04-09 23:04 UTC
