### ISSUE TITLE
Error in playback of 50XC6C-tnE4

### ISSUE THREAD

**Issue by RorickTech** [jagrosh/MusicBot#422] opened 2020-05-29 05:56 UTC
Music Bot Version 2.8.0 failing to play any requested song requested by name or direct URL, reporting:

"Error in playback of [URL link]"
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.

Any suggestions?
![Capture](https://user-images.githubusercontent.com/29452502/83226291-7dda8400-a136-11ea-85bc-b199b2f41ba8.PNG)

**Comment by jagrosh** [comment] 2020-05-29 05:57
Duplicate of #417

**Closed by jagrosh** 2020-05-29 05:57 UTC
