### ISSUE TITLE
[Bug Report] Received non-success response code 404

### ISSUE THREAD

**Issue by LuisVervaet** [jagrosh/MusicBot#370] opened 2020-03-23 21:20 UTC
**Describe the bug**
Every time I try playing music I get

Received non-success response code 404
and
Error in playback of XXXXXX

**To Reproduce**
1. Play {link or song}

**Expected behavior**
Supposed to play audio.

**Screenshots**
![image](https://user-images.githubusercontent.com/39219859/77364246-85db0980-6d2a-11ea-861f-5106c9f45b2c.png)

**Debug Info**
```
System Properties:
  java.version = 1.8.0_232
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_232-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.7
  Owner = 245653078794174465
  Prefix = ;;
  AltPrefix = @mention
  MaxSeconds = 0
  NPImages = true
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.34

Runtime Information:
  Total Memory = 16
  Used Memory = 14

Discord Information:
  ID = 622466849489027113
  Guilds = 2
  Users = 41
```

**Comment by jagrosh** [comment] 2020-03-23 21:21
Duplicate of #369, this will be fixed in the next update

**Closed** 2020-05-30 19:41 UTC
