### ISSUE TITLE
[Feature Request] Adding an option to bass-boost songs 

### ISSUE THREAD

**Issue by PraiseLag** [jagrosh/MusicBot#558] opened 2020-11-05 19:34 UTC
Is your feature request related to a problem? Please describe.
No, it's not a problem more a suggestion that me and my friends thought of.

Describe the solution you'd like
I would like an option to have a bass-boost mode

Describe the basic flow/steps of using this feature
How this feature would be used:

1. by doing a command like (prefix) bass-boost on and then it would bass-boost the song and 
2. Then to turn it off just do something like (prefix) bass-boost off
3. Basically how some of the other bots have for example "octave"

Additional context
I don't really have any other things to say but thanks for the bot.

**Comment by jagrosh** [comment] 2020-11-05 20:12
Duplicate of #475

**Closed by jagrosh** 2020-11-05 20:12 UTC
